const KEY='gcp-accessibility-v1';
const DEFAULTS={contrast:false,largeText:false,reducedMotion:false};
let lastPage='';
function load(){try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...DEFAULTS}}}
let prefs=load();
function save(){try{localStorage.setItem(KEY,JSON.stringify(prefs))}catch{}}
export function applyAccessibilityPrefs(){const root=document.documentElement;root.classList.toggle('gcp-high-contrast',!!prefs.contrast);root.classList.toggle('gcp-large-text',!!prefs.largeText);root.classList.toggle('gcp-reduce-motion',!!prefs.reducedMotion)}
export function accessibilityButton(){return `<button class="gcp-a11y-button" id="gcpAccessibility" aria-label="Acessibilidade" aria-haspopup="dialog" aria-expanded="false">Aa</button>`}
export function accessibilityLayer(){return `<div class="gcp-a11y-layer" id="gcpA11yLayer" hidden><section class="gcp-a11y-card" role="dialog" aria-modal="true" aria-labelledby="gcpA11yTitle"><header><div><span>ACESSIBILIDADE</span><h2 id="gcpA11yTitle">Como você quer jogar?</h2></div><button id="gcpA11yClose" aria-label="Fechar acessibilidade">×</button></header><div class="gcp-a11y-options"><button data-a11y="contrast" aria-pressed="${prefs.contrast}"><b>Contraste forte</b><span>Textos e controles mais definidos</span></button><button data-a11y="largeText" aria-pressed="${prefs.largeText}"><b>Texto maior</b><span>Aumenta o tamanho sem desmontar a tela</span></button><button data-a11y="reducedMotion" aria-pressed="${prefs.reducedMotion}"><b>Reduzir movimento</b><span>Menos animações e transições</span></button></div><footer><span>Atalhos: Alt+1 Início • Alt+2 Plantel • Alt+3 Jogo • Alt+4 Mercado • Alt+5 Notificações</span></footer></section></div><div class="gcp-sr-only" id="gcpLive" aria-live="polite" aria-atomic="true"></div>`}
function closeLayer(){const layer=document.querySelector('#gcpA11yLayer'),button=document.querySelector('#gcpAccessibility');if(layer)layer.hidden=true;if(button)button.setAttribute('aria-expanded','false')}
function openLayer(){const layer=document.querySelector('#gcpA11yLayer'),button=document.querySelector('#gcpAccessibility');if(!layer)return;layer.hidden=false;if(button)button.setAttribute('aria-expanded','true');requestAnimationFrame(()=>layer.querySelector('button')?.focus())}
function togglePref(name,button){prefs[name]=!prefs[name];save();applyAccessibilityPrefs();button?.setAttribute('aria-pressed',String(!!prefs[name]));announce(`${button?.querySelector('b')?.textContent||'Opção'} ${prefs[name]?'ativada':'desativada'}`)}
export function announce(text){const live=document.querySelector('#gcpLive');if(!live)return;live.textContent='';setTimeout(()=>{live.textContent=String(text||'')},20)}
function interactiveFallback(root){root.querySelectorAll('[data-squad-player],[data-market-player],[data-club-id],[data-country],[data-league]').forEach(el=>{if(/^(BUTTON|A|INPUT|SELECT|TEXTAREA)$/.test(el.tagName))return;el.setAttribute('role','button');if(!el.hasAttribute('tabindex'))el.tabIndex=0;if(el.dataset.a11yKey)return;el.dataset.a11yKey='1';el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})})}
function labelControls(root){root.querySelectorAll('button').forEach(b=>{if(!b.hasAttribute('type'))b.type='button';if(!b.getAttribute('aria-label')&&!b.textContent.trim()){const title=b.getAttribute('title');if(title)b.setAttribute('aria-label',title)}});root.querySelectorAll('img').forEach(img=>{if(!img.hasAttribute('alt'))img.alt=img.getAttribute('title')||''});root.querySelectorAll('.table-wrap,.fixture-list,.feed,.cd-report-grid,.job-grid,.competition-grid,.achievement-grid').forEach(el=>{if(!el.hasAttribute('tabindex'))el.tabIndex=0;el.setAttribute('role','region');if(!el.getAttribute('aria-label'))el.setAttribute('aria-label','Conteúdo rolável do jogo')});root.querySelectorAll('[data-page]').forEach(el=>{if(el.dataset.page===root.dataset.page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
export function enhanceAccessibility(root,page){applyAccessibilityPrefs();labelControls(root);interactiveFallback(root);const main=root.querySelector('#gameContent');if(main){main.setAttribute('role','main');main.setAttribute('aria-label','Área principal do Golaço Clash')}if(page&&page!==lastPage){lastPage=page;announce(`Tela ${page}`)}}
export function bindAccessibility(render){applyAccessibilityPrefs();document.querySelector('#gcpAccessibility')?.addEventListener('click',openLayer);document.querySelector('#gcpA11yClose')?.addEventListener('click',closeLayer);document.querySelector('#gcpA11yLayer')?.addEventListener('click',e=>{if(e.target.id==='gcpA11yLayer')closeLayer()});document.querySelectorAll('[data-a11y]').forEach(b=>b.addEventListener('click',()=>togglePref(b.dataset.a11y,b)));if(window.__gcpA11yKeys)return;window.__gcpA11yKeys=true;document.addEventListener('keydown',e=>{const typing=/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||'');if(e.key==='Escape'){closeLayer();const more=document.querySelector('.gcp-mobile-more');if(more)more.hidden=true;const quick=document.querySelector('#gcpQuickLayer');if(quick)quick.hidden=true;return}if(typing||!e.altKey)return;const pages={Digit1:'dashboard',Digit2:'squad',Digit3:'calendar',Digit4:'market',Digit5:'notifications'},page=pages[e.code];if(!page)return;e.preventDefault();const target=document.querySelector(`[data-page="${page}"]`);if(target)target.click();else if(render){window.__gcpKeyboardPage=page}});document.addEventListener('click',async e=>{const b=e.target.closest('#fullscreen');if(!b)return;e.preventDefault();e.stopImmediatePropagation();try{if(document.fullscreenElement)await document.exitFullscreen?.();else await document.documentElement.requestFullscreen?.();announce(document.fullscreenElement?'Tela cheia ativada':'Tela cheia desativada')}catch{announce('Tela cheia não disponível neste navegador')}},true)}
