import { state,currentClub,nextFixture,squad,ownedIds,soldIds,gameDate,addYears,clubBudgetBase,persist,storePlayerState,ensurePlayers,resetCareer,formatCurrency,formatDate } from './state.js';
import { simulateFixture,applyMatchFitness,evaluateOffer,playerInterest } from './game.js';
import { marketResults } from './football-pages.js';

export function bind(render){
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.selectedMarketPlayerId=null;state.selectedSquadPlayerId=null;state.marketPageIndex=0;render();if(['dashboard','squad','market','calendar'].includes(state.page))ensurePlayers(render);});
  document.querySelector('#goCover')?.addEventListener('click',()=>{state.screen='cover';render();});
  document.querySelector('#fullscreen')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());
  document.querySelector('#playNext')?.addEventListener('click',()=>playNext(render));
  document.querySelector('#retryPlayers')?.addEventListener('click',()=>{state.world.players=null;state.playersReady=false;ensurePlayers(render);});
  document.querySelectorAll('[data-squad-player]').forEach(el=>el.onclick=()=>{state.selectedSquadPlayerId=el.dataset.squadPlayer;render();});
  document.querySelector('#renewPlayer')?.addEventListener('click',()=>renew(render));
  document.querySelector('#sellPlayer')?.addEventListener('click',()=>sell(render));
  document.querySelector('#fireCoach')?.addEventListener('click',()=>fireCoach(render));
  document.querySelectorAll('[data-hire-coach]').forEach(el=>el.onclick=()=>hireCoach(el.dataset.hireCoach,render));
  bindMarket(render);
  document.querySelector('#saveNow')?.addEventListener('click',()=>{persist();alert('Carreira salva.');});
  document.querySelector('#exportSave')?.addEventListener('click',exportSave);
  document.querySelector('#resetSave')?.addEventListener('click',()=>{if(confirm('Apagar a carreira atual?')){resetCareer();render();}});
}
function bindMarket(render){
  const all=state.world?.players?state.world.marketPlayers(state.save.clubId,ownedIds(),soldIds()):[];
  const rerender=()=>{const root=document.querySelector('#marketResults');if(!root)return;const q=document.querySelector('#marketSearch')?.value||'',pos=document.querySelector('#marketPosition')?.value||'',ovr=Number(document.querySelector('#marketOvr')?.value||0);root.innerHTML=marketResults(all,q,pos,ovr);wireRows();};
  const wireRows=()=>{document.querySelectorAll('[data-market-player]').forEach(el=>el.onclick=()=>{state.selectedMarketPlayerId=el.dataset.marketPlayer;render();});document.querySelector('#prevMarket')?.addEventListener('click',()=>{state.marketPageIndex--;rerender();});document.querySelector('#nextMarket')?.addEventListener('click',()=>{state.marketPageIndex++;rerender();});};
  document.querySelector('#marketFilter')?.addEventListener('click',()=>{state.marketPageIndex=0;rerender();});
  document.querySelector('#marketSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){state.marketPageIndex=0;rerender();}});
  wireRows();
  document.querySelector('#closeMarket')?.addEventListener('click',()=>{state.selectedMarketPlayerId=null;render();});
  document.querySelector('#marketModal')?.addEventListener('click',e=>{if(e.target.id==='marketModal'){state.selectedMarketPlayerId=null;render();}});
  document.querySelector('#sendOffer')?.addEventListener('click',()=>sendOffer(render));
}
async function playNext(render){
  if(!state.playersReady)await ensurePlayers(render);const fx=nextFixture();if(!fx)return;const players=squad();if(players.length<11){alert('Não foi possível montar uma escalação com a base carregada.');return;}
  const result=simulateFixture({save:state.save,fixture:fx,nextFixture:nextFixture(1),squad:players,opponentClub:state.world.findClub(fx.opponentId)});
  const recovery=nextFixture(1)?Math.max(2,Math.round((new Date(`${nextFixture(1).date}T12:00:00Z`)-new Date(`${fx.date}T12:00:00Z`))/86400000)):7;
  applyMatchFitness(players,result.plan.starters,result.plan.bench,recovery);storePlayerState(players);fx.played=true;fx.result=`${result.gf}-${result.ga}`;
  state.save.matches.push({date:fx.date,competition:fx.competition,opponentName:fx.opponentName,home:fx.home,gf:result.gf,ga:result.ga,xg:result.xg,xga:result.xga,possession:result.possession,shots:result.shots,shotsAgainst:result.shotsAgainst,lineupOverall:result.plan.lineupOverall,rotation:result.plan.rotation,lineup:result.plan.starters.map(p=>({id:p.id,name:p.name,overall:p.overall}))});
  state.save.table.played++;state.save.table.gf+=result.gf;state.save.table.ga+=result.ga;
  if(result.gf>result.ga){state.save.table.wins++;state.save.table.points+=3;state.save.fanTrust+=1.3;state.save.boardTrust+=.7;}else if(result.gf===result.ga){state.save.table.draws++;state.save.table.points++;}else{state.save.table.losses++;state.save.fanTrust-=1.2;state.save.boardTrust-=.7;}
  state.save.nextFixtureIndex++;state.save.date=fx.date;state.save.news.unshift({date:fx.date,title:`${result.gf>result.ga?'Vitória':result.gf<result.ga?'Derrota':'Empate'}: ${result.gf}–${result.ga} contra ${fx.opponentName}`,body:`${state.save.coach.name} usou ${result.plan.rotation>=.4?'time misto':result.plan.rotation>=.15?'rodízio leve':'força máxima'} (OVR ${result.plan.lineupOverall}). ${result.plan.reason}`});persist();showReport(fx,result,render);
}
function showReport(fx,r,render){const c=currentClub(),app=document.querySelector('#app');app.innerHTML=`<section class="report-screen"><div class="report-card card"><span class="eyebrow">${fx.competition} • ${formatDate(fx.date)}</span><div class="report-score"><div><b>${c.name}</b></div><strong>${r.gf}<i>–</i>${r.ga}</strong><div><b>${fx.opponentName}</b></div></div><div class="match-stats"><div><span>Posse</span><b>${r.possession}%</b><em>${100-r.possession}%</em></div><div><span>Finalizações</span><b>${r.shots}</b><em>${r.shotsAgainst}</em></div><div><span>xG</span><b>${r.xg}</b><em>${r.xga}</em></div></div><div class="card inner"><span class="eyebrow">ESCALAÇÃO DE ${state.save.coach.name}</span><p>${r.plan.reason}</p><div class="lineup-chips">${r.plan.starters.map(p=>`<span>${p.name} <b>${p.overall}</b></span>`).join('')}</div></div><button class="button big full" id="afterMatch">Voltar ao gabinete</button></div></section>`;document.querySelector('#afterMatch').onclick=()=>{state.screen='game';state.page='dashboard';render();};}
function renew(render){const p=squad().find(x=>String(x.id)===String(state.selectedSquadPlayerId));if(!p)return;const until=addYears(gameDate(),3);state.save.playerContracts[p.id]={until};p.contractExpiration=until;state.save.news.unshift({date:gameDate(),title:`${p.name} renova contrato`,body:`Novo vínculo até ${formatDate(until)}.`});persist();render();}
function sell(render){const p=squad().find(x=>String(x.id)===String(state.selectedSquadPlayerId));if(!p)return;const offer=Math.round((p.marketValue||1e6)*(.9+Math.random()*.25)/10000)*10000;if(!confirm(`Proposta de ${formatCurrency(offer)} por ${p.name}. Aceitar?`))return;state.save.soldPlayerIds.push(String(p.id));state.save.acquiredPlayerIds=state.save.acquiredPlayerIds.filter(id=>String(id)!==String(p.id));state.save.cash+=offer;state.save.transferBudget+=offer;state.save.transactions.push({date:gameDate(),type:'Venda',description:p.name,amount:offer});persist();state.selectedSquadPlayerId=null;render();}
function fireCoach(render){const cost=Math.round(clubBudgetBase(currentClub())*(state.save.coach?.contractUntil ? .025 : .012));if(!confirm(`Demitir ${state.save.coach.name}? Custo: ${formatCurrency(cost)}.`))return;state.save.cash-=cost;state.save.transactions.push({date:gameDate(),type:'Rescisão',description:`Demissão de ${state.save.coach.name}`,amount:-cost});state.save.coach={name:'Técnico interino',original:false,hiredDate:gameDate(),contractUntil:addYears(gameDate(),1)};persist();render();}
function hireCoach(id,render){const source=state.world.findClub(id);if(!source?.coachName)return;const cost=Math.round(clubBudgetBase(source)*.035/100000)*100000;if(state.save.cash<cost){alert('Caixa insuficiente.');return;}if(!confirm(`Contratar ${source.coachName}, do ${source.name}, por compensação estimada de ${formatCurrency(cost)}?`))return;if((currentClub().teamOverall||72)<(source.teamOverall||72)-8&&Math.random()<.35){alert('O treinador recusou o projeto.');return;}state.save.cash-=cost;state.save.coach={name:source.coachName,original:false,hiredDate:gameDate(),contractUntil:addYears(gameDate(),2)};state.save.transactions.push({date:gameDate(),type:'Treinador',description:source.coachName,amount:-cost});persist();render();}
function sendOffer(render){const p=state.world.marketPlayers(state.save.clubId,ownedIds(),soldIds()).find(x=>String(x.id)===String(state.selectedMarketPlayerId));if(!p)return;const offer=Number(document.querySelector('#offerValue').value),feedback=document.querySelector('#offerFeedback');if(!offer||offer>state.save.transferBudget){feedback.innerHTML='<p class="negative">Proposta inválida ou acima do orçamento.</p>';return;}const seller=state.world.findClub(p.currentClubId),decision=evaluateOffer(p,offer,currentClub(),seller),interest=playerInterest(p,currentClub(),seller);if(!decision.accepted){feedback.innerHTML=`<div class="offer-feedback warn"><b>${decision.reason}</b><p>Contraproposta: ${formatCurrency(decision.counter)}</p></div>`;return;}if(!interest.interested){feedback.innerHTML=`<div class="offer-feedback warn"><b>Jogador recusou.</b><p>${interest.reason}</p></div>`;return;}const years=p.age>=31?2:4,until=addYears(gameDate(),years);if(!confirm(`Fechar ${p.name} por ${formatCurrency(offer)} e contrato de ${years} anos?`))return;state.save.transferBudget-=offer;state.save.cash-=offer;state.save.acquiredPlayerIds.push(String(p.id));state.save.playerContracts[p.id]={until,salary:p.estimatedWage};state.save.transactions.push({date:gameDate(),type:'Compra',description:p.name,amount:-offer});state.save.news.unshift({date:gameDate(),title:`${p.name} contratado`,body:`Transferência por ${formatCurrency(offer)}. Contrato até ${formatDate(until)}.`});state.selectedMarketPlayerId=null;persist();render();}
function exportSave(){const blob=new Blob([JSON.stringify(state.save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='football-president-save.json';a.click();URL.revokeObjectURL(url);}
