const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const addDays=(date,days)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
const hash=s=>[...String(s)].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261);
function randFrom(seed,shift=1){let x=(seed+shift*2654435761)>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295}
export function ensureBoardState(save,club){
 save.board??={objectives:[],sponsor:null,sponsorOffers:[],financialStatus:'HEALTHY',ownerRequests:[],evaluations:[],lastSponsorRefresh:null,lastReviewMonth:null};
 if(!save.board.objectives.length)save.board.objectives=buildObjectives(save,club);
 if(!save.board.sponsorOffers.length)refreshSponsorOffers(save,club,save.date||'2026-08-14');
 return save.board;
}
export function buildObjectives(save,club){const ovr=club?.teamOverall||72,rep=club?.reputation||ovr,target=ovr>=88?4:ovr>=82?6:ovr>=76?10:ovr>=70?14:18;return[
 {id:'LEAGUE',label:`Terminar entre os ${target} primeiros`,target,type:'POSITION',weight:40,status:'PENDING'},
 {id:'FINANCE',label:'Encerrar a temporada sem aumentar a dívida',type:'DEBT_CONTROL',weight:20,status:'PENDING'},
 {id:'YOUTH',label:rep>=82?'Dar minutos a pelo menos um jovem':'Melhorar a estrutura de base',type:'YOUTH',weight:15,status:'PENDING'},
 {id:'CUP',label:ovr>=86?'Chegar às fases finais de uma copa':'Ser competitivo nas copas',type:'CUP',weight:15,status:'PENDING'},
 {id:'TRUST',label:'Manter confiança da torcida acima de 55%',type:'FAN_TRUST',weight:10,status:'PENDING'}
]}
export function refreshSponsorOffers(save,club,date){ensureBoardStateShallow(save);const seed=hash(`${club?.name}-${save.season}-${date}`),base=Math.max(1_000_000,(save.financialModel?.sponsorRevenue||10_000_000));const brands=['Apex Sports','Vértice Bank','Nova Energy','Orbit Mobile','PrimeBet Sports','Atlas Airways','Flux Tech','Titan Motors','Nexo Telecom'];save.board.sponsorOffers=Array.from({length:3},(_,i)=>{const prestige=.75+randFrom(seed,i+1)*.75,annual=Math.round(base*prestige/100000)*100000,bonus=Math.round(annual*(.08+randFrom(seed,i+4)*.18)/50000)*50000;return{id:`sponsor-${date}-${i}`,name:brands[(seed+i*3)%brands.length],annualValue:annual,titleBonus:bonus,years:1+Math.floor(randFrom(seed,i+8)*3),minLeagueFinish:randFrom(seed,i+11)>.55?Math.max(1,Math.round(12-(club?.teamOverall||72-65)/3)):null,expires:addDays(date,30)}});save.board.lastSponsorRefresh=date;return save.board.sponsorOffers}
function ensureBoardStateShallow(save){save.board??={objectives:[],sponsor:null,sponsorOffers:[],financialStatus:'HEALTHY',ownerRequests:[],evaluations:[],lastSponsorRefresh:null,lastReviewMonth:null};return save.board}
export function signSponsor(save,offerId,date){const b=ensureBoardStateShallow(save),offer=b.sponsorOffers.find(x=>x.id===offerId);if(!offer)return{ok:false,message:'Oferta não encontrada.'};b.sponsor={...offer,start:date,endSeasonNo:(save.seasonNo||1)+offer.years-1};b.sponsorOffers=[];save.financialModel.sponsorRevenue=offer.annualValue;save.news.unshift({date,title:`Novo patrocinador: ${offer.name}`,body:`Contrato de ${offer.years} ano(s), ${moneyText(offer.annualValue)} por temporada, mais bônus.`});return{ok:true,offer}}
export function sponsorMonthlyPayment(save,date){const b=ensureBoardStateShallow(save);if(!b.sponsor)return 0;save.sponsorPaidMonths??=[];const key=date.slice(0,7);if(save.sponsorPaidMonths.includes(key))return 0;save.sponsorPaidMonths.push(key);const amount=Math.round(b.sponsor.annualValue/12);save.cash+=amount;save.transactions.push({date,type:'Patrocínio',description:b.sponsor.name,amount});return amount}
export function financialCompliance(save){ensureBoardStateShallow(save);const f=save.financialModel||{},history=f.history||[],last12=history.slice(-12),rev=last12.reduce((s,x)=>s+(x.revenue||0),0),exp=last12.reduce((s,x)=>s+(x.expenses||0),0)+(save.presidentStats?.moneySpent||0)*.08,debt=f.debt||0,loss=exp-rev;let status='HEALTHY';if(debt>Math.max(20_000_000,rev*.8)||loss>Math.max(30_000_000,rev*.55))status='WARNING';if(debt>Math.max(75_000_000,rev*1.8)||loss>Math.max(100_000_000,rev*1.25))status='BREACH_RISK';save.board.financialStatus=status;return{status,revenue:rev,expenses:exp,loss,debt}}
export function reviewBoard(save,club,position,date){const b=ensureBoardState(save,club),finance=financialCompliance(save);let score=50,completed=0;for(const obj of b.objectives){let ok=false;if(obj.type==='POSITION')ok=position&&position<=obj.target;if(obj.type==='DEBT_CONTROL')ok=finance.status==='HEALTHY';if(obj.type==='YOUTH')ok=(save.youth||[]).some(y=>y.promoted)||(save.facilities?.academy||0)>=6;if(obj.type==='CUP')ok=(save.competitionState?.titles||[]).length>0||(save.competitionState?.eliminated||[]).some(x=>/Quartas|Semifinal|Final/.test(x.round||''));if(obj.type==='FAN_TRUST')ok=(save.fanTrust||0)>=55;obj.status=ok?'COMPLETED':'FAILED';if(ok){score+=obj.weight*.65;completed++}else score-=obj.weight*.45}score+=((save.fanTrust||50)-50)*.18;score+=((save.relation||50)-50)*.08;if(finance.status==='BREACH_RISK')score-=15;score=clamp(Math.round(score),0,100);save.boardTrust=clamp(Math.round((save.boardTrust||60)*.55+score*.45),0,100);b.evaluations.push({date,season:save.season,score,completed,total:b.objectives.length,financialStatus:finance.status});return{score,completed,total:b.objectives.length,financialStatus:finance.status}}
export function requestOwnerFunds(save,date){ensureBoardStateShallow(save);const cooldown=save.board.ownerRequests.at(-1);if(cooldown&&days(cooldown.date,date)<180)return{ok:false,message:'O conselho não aceita um novo pedido de aporte ainda.'};const trust=save.boardTrust||60,chance=clamp(.2+(trust-50)*.012,0.08,.85),accepted=Math.random()<chance,amount=accepted?Math.round(Math.max(2_000_000,(save.transferBudget||10_000_000)*(.08+Math.random()*.18))/100000)*100000:0;save.board.ownerRequests.push({date,accepted,amount});if(accepted){save.cash+=amount;save.transferBudget+=amount;save.news.unshift({date,title:'Aporte aprovado pelo conselho',body:`O clube recebe ${moneyText(amount)} para reforçar o projeto.`})}else{save.boardTrust=clamp(save.boardTrust-2,0,100);save.news.unshift({date,title:'Pedido de aporte recusado',body:'O conselho entende que o clube deve trabalhar com o orçamento atual.'})}return{ok:accepted,amount,message:accepted?'Aporte aprovado.':'Pedido recusado.'}}
function days(a,b){return Math.floor((new Date(`${b}T12:00:00Z`)-new Date(`${a}T12:00:00Z`))/86400000)}
const moneyText=v=>`€${Math.round((v||0)/1_000_000*10)/10}M`;
