import {coachPage as baseCoachPage,coachResults} from './coach-v2.js';
import {state,esc,squad,nextFixture,teamOverall} from './state.js';
import {coachGameplayProfile} from './coach-profile.js';
import {coachSelection,setPieceTakers} from './game-v3.js';
export {coachResults};
const pct=v=>`${Math.round(v)}%`;
function meter(label,value){return `<div class="cd-tactic-meter"><div><span>${label}</span><b>${value}</b></div><i><em style="width:${value}%"></em></i></div>`}
function tacticalPitch(profile,plan){const rows={GK:[],DEF:[],MID:[],ATT:[]};for(const p of plan?.starters||[])rows[group(p)].push(p);const row=(key,label)=>`<div class="cd-pitch-row ${key.toLowerCase()}"><small>${label}</small><div>${rows[key].map(p=>`<span title="${esc(p.name)}"><b>${esc(short(p.name))}</b><i>${p.overall}</i></span>`).join('')}</div></div>`;return `<div class="cd-tactic-pitch"><div class="cd-pitch-lines"></div>${row('ATT','ATAQUE')}${row('MID','MEIO')}${row('DEF','DEFESA')}${row('GK','GOL')}</div>`}
function short(name){const a=String(name||'').trim().split(/\s+/);return a.length>1?a[a.length-1]:a[0]||'?'}
function group(p){const x=`${p.position||''} ${p.subPosition||''}`.toLowerCase();if(/goal|keeper/.test(x))return'GK';if(/defen|back/.test(x))return'DEF';if(/mid|wing/.test(x))return'MID';return'ATT'}
export function coachPage(){const coach={...state.save.coach,reputation:state.save.coach?.reputation||72},p=coachGameplayProfile(coach),players=squad(),fx=nextFixture(),plan=players.length>=11&&fx?coachSelection(players,fx,nextFixture(1),teamOverall(),coach):null,set=plan?.setPieces||setPieceTakers(players.slice(0,11),p);return `${baseCoachPage()}<section class="cd-coach-lab"><div class="cd-coach-lab-head"><div><span class="eyebrow">CENTRO TÁTICO</span><h2>Ideias de ${esc(coach.name)}</h2><p>O presidente acompanha. O treinador decide a forma de jogar e a escalação.</p></div><div class="cd-formation-badge"><span>FORMAÇÃO BASE</span><b>${esc(p.preferredFormation)}</b><small>${esc(p.style)}</small></div></div><div class="cd-tactical-grid"><div class="card cd-tactical-board">${tacticalPitch(p,plan)}<div class="cd-tactic-tags"><span>${esc(p.buildUp)}</span><span>${esc(p.pressLabel)}</span><span>${esc(p.lineLabel)}</span><span>${esc(p.widthLabel)}</span><span>${esc(p.tempoLabel)}</span><span>${esc(p.transitionLabel)}</span>${p.offsideTrap?'<span>Linha de impedimento</span>':''}</div></div><div class="card cd-tactic-details"><h3>Comportamento</h3>${meter('Pressão',p.pressing)}${meter('Linha defensiva',p.defensiveLine)}${meter('Posse',p.possessionBias)}${meter('Verticalidade',p.directness)}${meter('Risco ofensivo',p.attackingRisk)}${meter('Rodízio',p.rotation)}<div class="cd-coach-notes"><b>Leitura do técnico</b>${p.notes.length?p.notes.map(n=>`<span>• ${esc(n)}</span>`).join(''):'<span>• abordagem equilibrada</span>'}</div></div></div><div class="grid grid-2"><div class="card cd-setpieces"><span class="eyebrow">BOLA PARADA E LIDERANÇA</span><div><span>Pênaltis</span><b>${esc(set.penalties?.name||'A definir')}</b></div><div><span>Faltas</span><b>${esc(set.freeKicks?.name||'A definir')}</b></div><div><span>Escanteios</span><b>${esc(set.corners?.name||'A definir')}</b></div><div><span>Capitão</span><b>${esc(set.captain?.name||'A definir')}</b></div></div><div class="card cd-next-plan"><span class="eyebrow">PRÓXIMO JOGO</span>${plan?`<h3>${plan.rotation>=.4?'Time misto':plan.rotation>=.15?'Rodízio':'Força máxima'} • OVR ${plan.lineupOverall}</h3><p>${esc(plan.reason)}</p><small>${esc(p.preferredFormation)} • ${esc(p.pressLabel)} • ${esc(p.lineLabel)}</small>`:'<h3>Escalação será definida quando houver jogadores disponíveis.</h3>'}</div></div><p class="subtle cd-gameplay-note">Os parâmetros táticos são identidade de gameplay estável para cada treinador; não são apresentados como estatística oficial do treinador real.</p></section>`}
