const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const region=club=>{const c=`${club.country} ${club.league}`.toLowerCase();if(/england|spain|france|ital|germany|portugal|netherlands|belgium|turk/.test(c))return'EUROPE';if(/brazil|argentina|uruguay|colombia|chile|paraguay|ecuador/.test(c))return'SOUTH_AMERICA';if(/saudi|japan|korea|qatar|uae|china/.test(c))return'ASIA';if(/united states|usa|mexico|canada|mls|usl/.test(c))return'NORTH_AMERICA';return'OTHER'};
export function ensureCompetitionState(save){save.competitionState??={eliminated:[],titles:[],continental:null,nationalCup:null};return save.competitionState}
function fallbackShootout(result,fixture){const seed=[...String(`${fixture.id}|${result.gf}|${result.ga}|${result.plan?.lineupOverall||70}|${fixture.opponentOverall||70}`)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,2166136261)>>>0;return(seed%1000)/1000<clamp(.5+((result.plan?.lineupOverall||70)-(fixture.opponentOverall||70))*.02,.25,.75)}
export function processKnockoutResult(save,fixture,result,club){if(!['CUP','CONTINENTAL','WORLD_CLUB'].includes(fixture.type))return null;const state=ensureCompetitionState(save),isDraw=result.gf===result.ga,won=result.gf>result.ga||(isDraw?(result.shootout?result.shootout.winner==='USER':fallbackShootout(result,fixture)):false),shootoutScore=isDraw&&result.shootout?`${result.shootout.user}-${result.shootout.opponent}`:null;if(!won){state.eliminated.push({season:save.season,competition:fixture.competition,round:fixture.round,date:fixture.date});const before=save.calendar.slice(0,save.nextFixtureIndex),after=save.calendar.slice(save.nextFixtureIndex).filter(f=>f.competition!==fixture.competition);save.calendar=[...before,...after];save.news.unshift({date:fixture.date,title:`Eliminado da ${fixture.competition}`,body:`A campanha terminou em ${fixture.round}${isDraw?` após decisão por pênaltis${shootoutScore?` (${shootoutScore})`:''}`:''}.`});return{advanced:false,penalties:isDraw,shootout:result.shootout||null}}
 const future=save.calendar.slice(save.nextFixtureIndex).some(f=>f.competition===fixture.competition);if(!future){state.titles.push({season:save.season,competition:fixture.competition,date:fixture.date});save.trophies??=[];save.trophies.push({season:save.season,name:fixture.competition});save.presidentStats.titles=(save.presidentStats.titles||0)+1;save.news.unshift({date:fixture.date,title:`CAMPEÃO: ${fixture.competition}`,body:`${club.name} conquista ${fixture.competition}${isDraw?` nos pênaltis${shootoutScore?` (${shootoutScore})`:''}`:''}!`});return{advanced:true,champion:true,penalties:isDraw,shootout:result.shootout||null}}
 save.news.unshift({date:fixture.date,title:`Classificado na ${fixture.competition}`,body:`O clube avança após ${fixture.round}${isDraw?` nos pênaltis${shootoutScore?` (${shootoutScore})`:''}`:''}.`});return{advanced:true,champion:false,penalties:isDraw,shootout:result.shootout||null}}
export function continentalFor(club,leaguePosition,wonNationalCup=false){const r=region(club);if(r==='EUROPE'){if(leaguePosition<=4)return{name:'UEFA Champions League',id:'UCL',type:'CONTINENTAL'};if(leaguePosition<=6||wonNationalCup)return{name:'UEFA Europa League',id:'UEL',type:'CONTINENTAL'};if(leaguePosition<=7)return{name:'UEFA Conference League',id:'UECL',type:'CONTINENTAL'}}if(r==='SOUTH_AMERICA'){if(leaguePosition<=6||wonNationalCup)return{name:'CONMEBOL Libertadores',id:'LIBERTADORES',type:'CONTINENTAL'};if(leaguePosition<=12)return{name:'CONMEBOL Sudamericana',id:'SUDAMERICANA',type:'CONTINENTAL'}}if(r==='ASIA'){if(leaguePosition<=3)return{name:'AFC Champions League Elite',id:'AFC_ELITE',type:'CONTINENTAL'};if(leaguePosition<=6)return{name:'AFC Champions League Two',id:'AFC_TWO',type:'CONTINENTAL'}}if(r==='NORTH_AMERICA'){if(leaguePosition<=4||wonNationalCup)return{name:'Concacaf Champions Cup',id:'CONCACAF_CC',type:'CONTINENTAL'}}return null}
function addDays(date,days){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function eligibleOpponents(world,club){const r=region(club);return world.clubs.filter(c=>String(c.id)!==String(club.id)&&region(c)===r).sort((a,b)=>(b.teamOverall||0)-(a.teamOverall||0)).slice(0,80)}
export function injectContinentalFixtures(save,club,world,competition,startDate){if(!competition)return[];const opponents=eligibleOpponents(world,club);if(!opponents.length)return[];const dates=[18,46,74,102,130,158,202,230,258,286,314],rounds=['Fase de liga 1','Fase de liga 2','Fase de liga 3','Fase de liga 4','Fase de liga 5','Fase de liga 6','Oitavas de final','Quartas de final','Semifinal','Semifinal - volta','Final'],fixtures=dates.map((d,i)=>{const o=opponents[(i*7+save.seasonNo)%opponents.length];return{id:`${competition.id}-${save.seasonNo}-${i}`,type:'CONTINENTAL',competition:competition.name,round:rounds[i],date:addDays(startDate,d),opponentId:o.id,opponentName:o.name,opponentOverall:o.teamOverall||75,home:i%2===0,importance:i>=6?1.75:1.45,played:false}});save.calendar.push(...fixtures);save.calendar.sort((a,b)=>a.date.localeCompare(b.date));save.competitionState.continental=competition;save.news.unshift({date:startDate,title:`Classificado para ${competition.name}`,body:`A nova temporada terá calendário continental.`});return fixtures}
export function maybeClubWorldCup(save,club,world,startDate){const year=Number(startDate.slice(0,4)),hasContinental=(save.trophies||[]).some(t=>/Champions League|Libertadores|Concacaf|AFC/.test(t.name));if(!hasContinental||year%4!==1)return[];const opponents=world.clubs.filter(c=>String(c.id)!==String(club.id)).sort((a,b)=>(b.teamOverall||0)-(a.teamOverall||0)).slice(0,24),fixtures=[];['Grupo 1','Grupo 2','Grupo 3','Oitavas','Quartas','Semifinal','Final'].forEach((round,i)=>{const o=opponents[(i*5+year)%opponents.length];if(!o)return;fixtures.push({id:`CWC-${year}-${i}`,type:'WORLD_CLUB',competition:'FIFA Club World Cup',round,date:addDays(startDate,310+i*5),opponentId:o.id,opponentName:o.name,opponentOverall:o.teamOverall||80,home:i%2===0,importance:i>=3?1.9:1.6,played:false})});save.calendar.push(...fixtures);save.calendar.sort((a,b)=>a.date.localeCompare(b.date));return fixtures}
export function nationalTeamWorldNews(save,date){const year=Number(date.slice(0,4));if(year%4===2&&date.slice(5,7)==='06'&&!save.worldCupNewsYears?.includes(year)){save.worldCupNewsYears??=[];save.worldCupNewsYears.push(year);save.news.unshift({date,title:'Copa do Mundo de seleções',body:'O mundo do futebol pausa para acompanhar a Copa do Mundo. O presidente segue administrando o clube durante o torneio.'})}}
