import { state,esc,nextFixture,squad,ownedIds,soldIds,formatCurrency,formatDate,contractLabel,normalizedName } from './state.js';
import { coachSelection,calculateTeamOverall,askingPrice } from './game.js';
import { loadingPlayers,noPlayers,ratingClass } from './views.js';

export function squadPage(){
  if(state.playersLoading)return `<div class="hero"><div><h1>Elenco</h1><p>O treinador escolhe quem joga.</p></div></div>${loadingPlayers()}`;
  if(!state.playersReady||!state.world.players?.length)return `<div class="hero"><div><h1>Elenco</h1></div></div>${noPlayers()}`;
  const players=squad().sort((a,b)=>(b.overall||0)-(a.overall||0)),fx=nextFixture();
  const plan=fx&&players.length>=11?coachSelection(players,fx,nextFixture(1),calculateTeamOverall(players)):null;
  const xi=new Set(plan?.starters.map(p=>String(p.id))||[]),selected=players.find(p=>String(p.id)===String(state.selectedSquadPlayerId));
  return `<div class="hero"><div><span class="eyebrow">ELENCO PROFISSIONAL</span><h1>${players.length} jogadores</h1><p>Você contrata, vende e renova. Quem entra em campo é decisão do técnico.</p></div><div class="ovr-block"><span>OVR</span><b>${calculateTeamOverall(players)}</b></div></div>${plan?`<div class="coach-plan card"><div><span class="eyebrow">PRÓXIMA ESCALAÇÃO PROVÁVEL</span><h2>${plan.rotation>=.4?'Time misto':plan.rotation>=.15?'Rodízio leve':'Força máxima'} • OVR ${plan.lineupOverall}</h2><p>${esc(plan.reason)}</p></div><div class="lineup-chips">${plan.starters.map(p=>`<span>${esc(p.name)} <b>${p.overall}</b></span>`).join('')}</div></div>`:''}<div class="split-view"><div class="table-wrap"><table><thead><tr><th></th><th>Jogador</th><th>Posição</th><th>OVR</th><th>POT</th><th>Energia</th><th>Contrato</th><th>Valor</th></tr></thead><tbody>${players.map(p=>`<tr class="clickable ${String(p.id)===String(state.selectedSquadPlayerId)?'selected':''}" data-squad-player="${p.id}"><td>${xi.has(String(p.id))?'<span class="pill ok">XI</span>':'<span class="pill">Banco</span>'}</td><td><b>${esc(p.name)}</b><small>${esc(p.nationality||'')}</small></td><td>${esc(p.subPosition||p.position)}</td><td><b class="rating ${ratingClass(p.overall)}">${p.overall}</b></td><td>${p.potential}</td><td>${Math.round(p.energy??100)}%</td><td>${contractLabel(p.contractExpiration)}<small>${p.contractExpiration?`até ${formatDate(p.contractExpiration)}`:''}</small></td><td>${p.marketValue?formatCurrency(p.marketValue):'—'}</td></tr>`).join('')}</tbody></table></div>${selected?playerPanel(selected):'<aside class="detail-panel card"><span class="eyebrow">DETALHES</span><h2>Selecione um jogador</h2><p class="subtle">Contrato, energia, valor e decisões do presidente.</p></aside>'}</div>`;
}
function playerPanel(p){return `<aside class="detail-panel card"><span class="eyebrow">JOGADOR DO CLUBE</span><div class="player-head"><div class="player-avatar">${esc(p.name.split(/\s+/).slice(-1)[0][0]||'?')}</div><div><h2>${esc(p.name)}</h2><p>${esc(p.subPosition||p.position)} • ${p.age??'—'} anos</p></div><b class="rating huge ${ratingClass(p.overall)}">${p.overall}</b></div><div class="fact-list compact"><div><span>Contrato restante</span><b>${contractLabel(p.contractExpiration)}</b></div><div><span>Fim do contrato</span><b>${formatDate(p.contractExpiration)}</b></div><div><span>Valor</span><b>${p.marketValue?formatCurrency(p.marketValue):'—'}</b></div><div><span>Salário semanal estimado</span><b>${formatCurrency(p.estimatedWage)}</b></div><div><span>Energia</span><b>${Math.round(p.energy??100)}%</b></div><div><span>Potencial</span><b>${p.potential}</b></div></div><div class="detail-actions"><button class="button secondary" id="renewPlayer">Renovar 3 anos</button><button class="button danger" id="sellPlayer">Ouvir proposta</button></div></aside>`;}
export function coachPage(){const coach=state.save.coach,candidates=state.world.clubs.filter(x=>x.coachName&&x.coachName!==coach?.name).sort((a,b)=>(b.teamOverall||0)-(a.teamOverall||0)).slice(0,30);return `<div class="hero"><div><span class="eyebrow">COMANDO TÉCNICO</span><h1>Treinador</h1><p>Ele decide formação, escalação, rodízio e substituições.</p></div></div><div class="coach-profile card"><div class="coach-avatar">${esc((coach?.name||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</div><div><span class="eyebrow">TÉCNICO ATUAL</span><h2>${esc(coach?.name||'Não informado')}</h2><p>${coach?.original?'Veio com o clube na base inicial.':`Contratado em ${formatDate(coach?.hiredDate)}.`}</p></div><div class="coach-contract"><span>CONTRATO RESTANTE</span><b>${coach?.contractUntil?contractLabel(coach.contractUntil):'Não informado na fonte'}</b><small>${coach?.contractUntil?`até ${formatDate(coach.contractUntil)}`:'O jogo não inventa a duração do vínculo inicial.'}</small></div><button class="button danger" id="fireCoach">Demitir</button></div><h2 class="section-title">Mercado de treinadores</h2><div class="coach-market">${candidates.map(x=>`<div class="coach-card card"><span>${esc(x.country)}</span><h3>${esc(x.coachName)}</h3><p>${esc(x.name)} • OVR ${x.teamOverall}</p><button class="button secondary" data-hire-coach="${esc(x.id)}">Abordar treinador</button></div>`).join('')}</div>`;}
export function marketPage(){
  if(state.playersLoading)return `<div class="hero"><div><h1>Mercado</h1><p>Jogadores de outros clubes.</p></div></div>${loadingPlayers()}`;
  if(!state.playersReady||!state.world.players?.length)return `<div class="hero"><div><h1>Mercado</h1></div></div>${noPlayers()}`;
  const all=state.world.marketPlayers(state.save.clubId,ownedIds(),soldIds()),selected=all.find(p=>String(p.id)===String(state.selectedMarketPlayerId));
  return `<div class="hero"><div><span class="eyebrow">MERCADO MUNDIAL</span><h1>Contratações</h1><p>${all.length.toLocaleString('pt-BR')} jogadores de outros clubes. Seus jogadores não aparecem aqui.</p></div><div><span class="subtle">Orçamento</span><div class="metric money">${formatCurrency(state.save.transferBudget)}</div></div></div><div class="market-toolbar card"><input id="marketSearch" placeholder="Buscar jogador ou clube…"><select id="marketPosition"><option value="">Todas as posições</option><option>Goalkeeper</option><option>Defence</option><option>Midfield</option><option>Attack</option></select><select id="marketOvr"><option value="0">Qualquer OVR</option><option value="85">85+</option><option value="80">80+</option><option value="75">75+</option><option value="70">70+</option></select><button class="button secondary" id="marketFilter">Filtrar</button></div><div id="marketResults">${marketResults(all,'','',0)}</div>${selected?`<div class="modal-backdrop" id="marketModal"><div class="transfer-modal card">${marketPanel(selected)}</div></div>`:''}`;
}
export function marketResults(all,search,position,minOvr){const q=normalizedName(search),filtered=all.filter(p=>(!q||normalizedName(`${p.name} ${p.currentClubName}`).includes(q))&&(!position||p.position===position)&&p.overall>=minOvr).sort((a,b)=>(b.overall||0)-(a.overall||0)||(b.marketValue||0)-(a.marketValue||0));const size=80,pages=Math.max(1,Math.ceil(filtered.length/size));state.marketPageIndex=Math.max(0,Math.min(state.marketPageIndex,pages-1));const list=filtered.slice(state.marketPageIndex*size,(state.marketPageIndex+1)*size);return `<div class="table-wrap"><table><thead><tr><th>Jogador</th><th>Clube</th><th>Posição</th><th>Idade</th><th>OVR</th><th>POT</th><th>Contrato</th><th>Valor</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.nationality||'')}</small></td><td>${esc(p.currentClubName||'—')}</td><td>${esc(p.subPosition||p.position)}</td><td>${p.age??'—'}</td><td><b class="rating ${ratingClass(p.overall)}">${p.overall}</b></td><td>${p.potential}</td><td>${contractLabel(p.contractExpiration)}<small>${formatDate(p.contractExpiration)}</small></td><td>${p.marketValue?formatCurrency(p.marketValue):'—'}</td><td><button class="button secondary compact" data-market-player="${p.id}">Negociar</button></td></tr>`).join('')}</tbody></table></div><div class="pagination"><button class="button ghost compact" id="prevMarket" ${state.marketPageIndex<=0?'disabled':''}>←</button><span>Página ${state.marketPageIndex+1} de ${pages} • ${filtered.length.toLocaleString('pt-BR')} resultados</span><button class="button ghost compact" id="nextMarket" ${state.marketPageIndex>=pages-1?'disabled':''}>→</button></div>`;}
function marketPanel(p){const ask=askingPrice(p);return `<button class="modal-close" id="closeMarket">×</button><span class="eyebrow">NEGOCIAÇÃO</span><div class="player-head"><div class="player-avatar">${esc(p.name.split(/\s+/).slice(-1)[0][0]||'?')}</div><div><h2>${esc(p.name)}</h2><p>${esc(p.currentClubName)} • ${esc(p.subPosition||p.position)}</p></div><b class="rating huge ${ratingClass(p.overall)}">${p.overall}</b></div><div class="grid grid-3 mini-stats"><div><span>Valor</span><b>${formatCurrency(p.marketValue)}</b></div><div><span>Contrato</span><b>${contractLabel(p.contractExpiration)}</b></div><div><span>Potencial</span><b>${p.potential}</b></div></div><div class="offer-box"><label>Proposta ao clube</label><input id="offerValue" type="number" value="${ask}" step="100000"><small>Pedido aproximado: ${formatCurrency(ask)}</small></div><button class="button big full" id="sendOffer">Enviar proposta</button><div id="offerFeedback"></div>`;}
