import * as base from './game-v2.js';
import {coachGameplayProfile,coachMatchModifiers} from './coach-profile.js';

export const leagueProfile=base.leagueProfile;
export const buildCalendar=base.buildCalendar;
export const calculateTeamOverall=base.calculateTeamOverall;
export const applyMatchFitness=base.applyMatchFitness;
export const askingPrice=base.askingPrice;
export const evaluateOffer=base.evaluateOffer;
export const playerInterest=base.playerInterest;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const DAY=86400000;
const daysBetween=(a,b)=>Math.round((new Date(`${b}T12:00:00Z`)-new Date(`${a}T12:00:00Z`))/DAY);
const hash=str=>[...String(str)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,2166136261)>>>0;
function rng(seed){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function goals(lambda,random){const L=Math.exp(-clamp(lambda,.15,3.9));let k=0,p=1;do{k++;p*=random()}while(p>L&&k<9);return k-1}
function group(p){const x=`${p.position||''} ${p.subPosition||''}`.toLowerCase();if(/goal|keeper|gole/.test(x))return'GK';if(/defen|back|zague|lateral/.test(x))return'DEF';if(/mid|meia|medio|volante|wing/.test(x))return'MID';return'ATT'}
function tacticalScore(p,profile,rotation){let s=(p.overall||65)*1.32+(p.energy??100)*(.09+rotation*.17)+(p.form??70)*.075;const g=group(p),sub=String(p.subPosition||'').toLowerCase();if(profile.pressing>=72&&g!=='GK')s+=(p.energy??100)*.035;if(profile.width>=70&&/wing|left|right|lateral/.test(sub))s+=2.1;if(profile.width<=44&&/central|centre|attacking midfield|defensive midfield/.test(sub))s+=1.8;if(profile.directness>=72&&g==='ATT')s+=1.4;if(profile.possessionBias>=72&&g==='MID')s+=1.7;if(profile.defensiveLine>=70&&g==='DEF'&&(p.energy??100)>=75)s+=1.2;if(profile.youthDevelopment>=76&&(p.age??99)<=21&&(p.potential||0)>(p.overall||0)+3)s+=1.7;if(profile.pragmatism>=76&&g==='DEF')s+=1.1;return s}
function pickGroup(players,g,count,used,profile,rotation){const list=players.filter(p=>group(p)===g&&!used.has(String(p.id))).sort((a,b)=>tacticalScore(b,profile,rotation)-tacticalScore(a,profile,rotation));const picked=list.slice(0,count);picked.forEach(p=>used.add(String(p.id)));return picked}
function rotationPlan(profile,fixture,nextFixture,teamOverall){const days=nextFixture?daysBetween(fixture.date,nextFixture.date):8,opp=fixture.opponentOverall||72,nextOpp=nextFixture?.opponentOverall||0,currentBig=fixture.importance>=1.4||opp>=teamOverall-1,nextBig=!!nextFixture&&(nextFixture.importance>fixture.importance+.12||nextOpp>=opp+5),tight=days<=4;let rotation=0,reason='Força máxima: o técnico vê este jogo como prioridade.';const tendency=(profile.rotation-55)/100;if(!currentBig&&tight&&nextBig){rotation=.36+Math.max(0,tendency*.35);reason=`Rodízio forte: há outro jogo exigente em ${days} dias.`}else if(!currentBig&&opp<=teamOverall-7){rotation=(tight?.34:.20)+Math.max(0,tendency*.28);reason=`Time misto: o adversário tem OVR ${opp} e o técnico preserva peças para o calendário.`}else if(tight){rotation=.12+Math.max(0,tendency*.22);reason=`Rodízio leve por calendário apertado: ${days} dias até o próximo jogo.`}if(profile.rotation<45)rotation*=.65;if(fixture.type==='CUP'&&fixture.importance>=1.5){rotation=Math.min(rotation,.10);reason='Mata-mata importante: o técnico reduz o rodízio.'}return{rotation:clamp(rotation,0,.58),reason,days}}
export function coachSelection(squad,fixture,nextFixture,teamOverall,coach={}){const profile=coachGameplayProfile(coach),r=rotationPlan(profile,fixture,nextFixture,teamOverall),players=squad.map(p=>({...p})),used=new Set(),shape=profile.shape;let starters=[...pickGroup(players,'GK',shape.GK,used,profile,r.rotation),...pickGroup(players,'DEF',shape.DEF,used,profile,r.rotation),...pickGroup(players,'MID',shape.MID,used,profile,r.rotation),...pickGroup(players,'ATT',shape.ATT,used,profile,r.rotation)];if(starters.length<11)starters=starters.concat(players.filter(p=>!used.has(String(p.id))).sort((a,b)=>tacticalScore(b,profile,r.rotation)-tacticalScore(a,profile,r.rotation)).slice(0,11-starters.length));if(r.rotation>.2&&players.length>15){const protectedList=[...starters].sort((a,b)=>(b.overall||0)-(a.overall||0));const benchPool=players.filter(p=>!starters.some(s=>String(s.id)===String(p.id))).sort((a,b)=>tacticalScore(b,profile,r.rotation)-tacticalScore(a,profile,r.rotation));const swaps=Math.min(4,Math.max(1,Math.round(r.rotation*7)));for(let i=0;i<swaps;i++){const star=protectedList[i],idx=benchPool.findIndex(p=>group(p)===group(star)&&(p.overall||0)>=(star.overall||0)-11);if(idx>=0){const rep=benchPool.splice(idx,1)[0];starters=starters.map(p=>String(p.id)===String(star.id)?rep:p);benchPool.push(star)}}}const ids=new Set(starters.map(p=>String(p.id))),bench=players.filter(p=>!ids.has(String(p.id))).sort((a,b)=>tacticalScore(b,profile,.28)-tacticalScore(a,profile,.28)).slice(0,9),lineupOverall=Math.round(starters.reduce((s,p)=>s+(p.overall||65),0)/Math.max(1,starters.length)),setPieces=setPieceTakers(starters,profile);return{starters,bench,lineupOverall,rotation:r.rotation,reason:r.reason,daysToNext:r.days,coachProfile:profile,preferredFormation:profile.preferredFormation,style:profile.style,setPieces}}
export function setPieceTakers(starters,profile){const score=p=>(p.overall||65)+(group(p)==='ATT'?4:group(p)==='MID'?3:0)+(p.form??70)/40,sorted=[...starters].sort((a,b)=>score(b)-score(a)),mid=[...starters].filter(p=>group(p)==='MID'||group(p)==='ATT').sort((a,b)=>score(b)-score(a)),captain=[...starters].sort((a,b)=>((b.age||24)*.22+(b.overall||65))-((a.age||24)*.22+(a.overall||65)));return{penalties:sorted[0]||null,freeKicks:mid[0]||sorted[0]||null,corners:mid[1]||mid[0]||null,captain:captain[0]||sorted[0]||null,aggression:profile.setPieceFocus}}
export function simulateFixture({save,fixture,nextFixture,squad,opponentClub}){const teamOverall=calculateTeamOverall(squad),coach={...save.coach,reputation:save.coach?.reputation||Math.max(60,Math.min(92,teamOverall))},m=coachMatchModifiers(coach),plan=coachSelection(squad,fixture,nextFixture,teamOverall,coach),opp=fixture.opponentOverall||opponentClub?.teamOverall||72,home=fixture.home?.18:-.06,diff=(plan.lineupOverall-opp)/10;const attack=m.attackBias*.20+m.pressBias*.07+m.tempoBias*.05+m.possessionBias*.04,defRisk=m.lineRisk*.08+m.attackBias*.08-m.profile.pragmatism/850,control=m.possessionBias*.12-m.directBias*.05;const xFor=1.24+diff*.42+home+attack,xAgainst=1.17-diff*.36-home*.45+defRisk,random=rng(hash(`${save.clubId}-${fixture.id}-${save.season}-${save.matches?.length||0}-${coach.name}`)+Date.now()%9973),gf=goals(xFor,random),ga=goals(xAgainst,random),possession=clamp(Math.round(50+(plan.lineupOverall-opp)*1.15+control*25+(random()-.5)*7),28,72),shots=Math.max(3,Math.round(8+xFor*4+random()*5)),shotsAgainst=Math.max(3,Math.round(8+xAgainst*4+random()*5)),xg=Math.max(.2,Math.round((xFor+(random()-.5)*.32)*100)/100),xga=Math.max(.2,Math.round((xAgainst+(random()-.5)*.32)*100)/100);return{gf,ga,possession,shots,shotsAgainst,xg,xga,teamOverall,plan,coachProfile:m.profile}}
