import * as base from './game.js';
import {coachGameplayProfile,coachMatchModifiers} from './coach-profile.js';

export const leagueProfile=base.leagueProfile;
export const buildCalendar=base.buildCalendar;
export const calculateTeamOverall=base.calculateTeamOverall;
export const applyMatchFitness=base.applyMatchFitness;
export const askingPrice=base.askingPrice;
export const evaluateOffer=base.evaluateOffer;
export const playerInterest=base.playerInterest;

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const DAY=86400000;
const daysBetween=(a,b)=>Math.round((new Date(`${b}T12:00:00Z`)-new Date(`${a}T12:00:00Z`))/DAY);
const hash=str=>[...String(str)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,2166136261)>>>0;
function rng(seed){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function goals(lambda,random){const L=Math.exp(-clamp(lambda,.15,3.85));let k=0,p=1;do{k++;p*=random()}while(p>L&&k<9);return k-1}
function group(p){const x=`${p?.position||''} ${p?.subPosition||''}`.toLowerCase();if(/goal|keeper|gole/.test(x))return'GK';if(/defen|back|zague|lateral/.test(x))return'DEF';if(/mid|meia|medio|volante|wing/.test(x))return'MID';return'ATT'}
function average(list,key,fallback){if(!list?.length)return fallback;return list.reduce((s,p)=>s+Number(p?.[key]??fallback),0)/list.length}
function weightedPick(list,weight,random){if(!list?.length)return null;const weights=list.map(x=>Math.max(.01,weight(x))),sum=weights.reduce((a,b)=>a+b,0);let r=random()*sum;for(let i=0;i<list.length;i++){r-=weights[i];if(r<=0)return list[i]}return list.at(-1)}
function playerSuitability(p,profile,rotation){let s=(p.overall||65)*1.34+(p.energy??100)*(.075+rotation*.19)+(p.form??70)*.08;const g=group(p),sub=String(p.subPosition||'').toLowerCase();if(profile.pressing>=72&&g!=='GK')s+=(p.energy??100)*.04;if(profile.width>=70&&/wing|left|right|lateral/.test(sub))s+=2.2;if(profile.width<=44&&/central|centre|attacking midfield|defensive midfield/.test(sub))s+=1.7;if(profile.directness>=72&&g==='ATT')s+=1.5;if(profile.possessionBias>=72&&g==='MID')s+=1.7;if(profile.defensiveLine>=70&&g==='DEF'&&(p.energy??100)>=74)s+=1.25;if(profile.youthDevelopment>=76&&(p.age??99)<=21&&(p.potential||0)>(p.overall||0)+3)s+=1.6;if(profile.pragmatism>=76&&g==='DEF')s+=1.05;return s}
function pickGroup(players,g,count,used,profile,rotation){const list=players.filter(p=>group(p)===g&&!used.has(String(p.id))).sort((a,b)=>playerSuitability(b,profile,rotation)-playerSuitability(a,profile,rotation));const picked=list.slice(0,count);picked.forEach(p=>used.add(String(p.id)));return picked}
function rotationPlan(profile,fixture,nextFixture,teamOverall){const days=nextFixture?daysBetween(fixture.date,nextFixture.date):8,opp=fixture.opponentOverall||72,nextOpp=nextFixture?.opponentOverall||0,currentBig=fixture.importance>=1.4||opp>=teamOverall-1,nextBig=!!nextFixture&&(nextFixture.importance>fixture.importance+.12||nextOpp>=opp+5),tight=days<=4;let rotation=0,reason='Força máxima: o técnico vê este jogo como prioridade.';const tendency=(profile.rotation-55)/100;if(!currentBig&&tight&&nextBig){rotation=.36+Math.max(0,tendency*.35);reason=`Rodízio forte: há outro jogo exigente em ${days} dias.`}else if(!currentBig&&opp<=teamOverall-7){rotation=(tight?.34:.20)+Math.max(0,tendency*.28);reason=`Time misto: o adversário tem OVR ${opp} e o técnico preserva peças para o calendário.`}else if(tight){rotation=.12+Math.max(0,tendency*.22);reason=`Rodízio leve por calendário apertado: ${days} dias até o próximo jogo.`}if(profile.rotation<45)rotation*=.65;if(fixture.type==='CUP'&&fixture.importance>=1.5){rotation=Math.min(rotation,.10);reason='Mata-mata importante: o técnico reduz o rodízio.'}return{rotation:clamp(rotation,0,.58),reason,days}}
export function setPieceTakers(starters,profile){const score=p=>(p.overall||65)+(group(p)==='ATT'?4:group(p)==='MID'?3:0)+(p.form??70)/40,sorted=[...starters].sort((a,b)=>score(b)-score(a)),mid=[...starters].filter(p=>group(p)==='MID'||group(p)==='ATT').sort((a,b)=>score(b)-score(a)),captain=[...starters].sort((a,b)=>((b.age||24)*.22+(b.overall||65))-((a.age||24)*.22+(a.overall||65)));return{penalties:sorted[0]||null,freeKicks:mid[0]||sorted[0]||null,corners:mid[1]||mid[0]||null,captain:captain[0]||sorted[0]||null,aggression:profile.setPieceFocus}}
export function coachSelection(squad,fixture,nextFixture,teamOverall,coach={}){const profile=coachGameplayProfile(coach),r=rotationPlan(profile,fixture,nextFixture,teamOverall),players=(squad||[]).map(p=>({...p})),used=new Set(),shape=profile.shape||{GK:1,DEF:4,MID:3,ATT:3};let starters=[...pickGroup(players,'GK',shape.GK,used,profile,r.rotation),...pickGroup(players,'DEF',shape.DEF,used,profile,r.rotation),...pickGroup(players,'MID',shape.MID,used,profile,r.rotation),...pickGroup(players,'ATT',shape.ATT,used,profile,r.rotation)];if(starters.length<11)starters=starters.concat(players.filter(p=>!used.has(String(p.id))).sort((a,b)=>playerSuitability(b,profile,r.rotation)-playerSuitability(a,profile,r.rotation)).slice(0,11-starters.length));if(r.rotation>.2&&players.length>15){const protectedList=[...starters].sort((a,b)=>(b.overall||0)-(a.overall||0)),benchPool=players.filter(p=>!starters.some(s=>String(s.id)===String(p.id))).sort((a,b)=>playerSuitability(b,profile,r.rotation)-playerSuitability(a,profile,r.rotation)),swaps=Math.min(4,Math.max(1,Math.round(r.rotation*7)));for(let i=0;i<swaps;i++){const star=protectedList[i],idx=benchPool.findIndex(p=>group(p)===group(star)&&(p.overall||0)>=(star.overall||0)-11);if(idx>=0){const rep=benchPool.splice(idx,1)[0];starters=starters.map(p=>String(p.id)===String(star.id)?rep:p);benchPool.push(star)}}}const ids=new Set(starters.map(p=>String(p.id))),bench=players.filter(p=>!ids.has(String(p.id))).sort((a,b)=>playerSuitability(b,profile,.28)-playerSuitability(a,profile,.28)).slice(0,9),lineupOverall=Math.round(starters.reduce((s,p)=>s+(p.overall||65),0)/Math.max(1,starters.length)),setPieces=setPieceTakers(starters,profile);return{starters,bench,lineupOverall,rotation:r.rotation,reason:r.reason,daysToNext:r.days,coachProfile:profile,preferredFormation:profile.preferredFormation,style:profile.style,setPieces}}
function syntheticOpponentPlan(opponentClub,overall){const coach={name:opponentClub?.coachName||`Técnico ${opponentClub?.name||'adversário'}`,reputation:overall},profile=coachGameplayProfile(coach),shape=profile.shape||{GK:1,DEF:4,MID:3,ATT:3},starters=[];for(const [role,count] of Object.entries(shape))for(let i=0;i<count;i++)starters.push({id:`opp-${role}-${i}`,name:role==='GK'?'Goleiro':`${role} ${i+1}`,position:role==='GK'?'Goalkeeper':role==='DEF'?'Defence':role==='MID'?'Midfield':'Attack',subPosition:'',overall,energy:100,form:70});return{starters,bench:[],lineupOverall:overall,rotation:0,reason:'O adversário montou a equipe conforme a identidade do seu treinador.',daysToNext:7,coachProfile:profile,preferredFormation:profile.preferredFormation,style:profile.style,setPieces:setPieceTakers(starters,profile)}}
function tacticalMatchup(att,def){let edge=0;const notes=[];if(att.pressing>=74&&def.buildUp==='Saída curta'){edge+=.07;notes.push('pressão sobre saída curta')}if(att.counterAttack>=74&&def.defensiveLine>=68){edge+=.08;notes.push('espaço para contra-ataque')}if(att.width>=70&&def.width<=46){edge+=.045;notes.push('amplitude contra bloco estreito')}if(att.directness>=72&&def.defensiveLine>=72){edge+=.04;notes.push('bola vertical nas costas da linha')}if(att.possessionBias>=74&&def.pressing<=48){edge+=.035;notes.push('controle territorial')}if(def.pragmatism>=78)edge-=.035;return{edge,notes}}
function contributors(plan,gf,random){const events=[],starters=plan.starters||[],scorerWeight=p=>group(p)==='ATT'?5.6:group(p)==='MID'?2.8:group(p)==='DEF'?.65:.08;for(let i=0;i<gf;i++){const scorer=weightedPick(starters,scorerWeight,random);if(!scorer)continue;const possible=starters.filter(x=>String(x.id)!==String(scorer.id)),assist=random()<.72?weightedPick(possible,p=>group(p)==='MID'?4.2:group(p)==='ATT'?2.7:1,random):null;events.push({scorerId:String(scorer.id),scorer:scorer.name,assistId:assist?String(assist.id):null,assist:assist?.name||null})}return events}
export function simulateFixture({save,fixture,nextFixture,squad,opponentClub,opponentSquad=[]}){const teamOverall=calculateTeamOverall(squad),coach={...save.coach,reputation:save.coach?.reputation||Math.max(60,Math.min(92,teamOverall))},userMods=coachMatchModifiers(coach),plan=coachSelection(squad,fixture,nextFixture,teamOverall,coach),oppBase=fixture.opponentOverall||opponentClub?.teamOverall||72,oppCoach={name:opponentClub?.coachName||`Técnico ${fixture.opponentName||'adversário'}`,reputation:oppBase},opponentPlan=opponentSquad?.length>=11?coachSelection(opponentSquad,{...fixture,home:!fixture.home,opponentOverall:plan.lineupOverall,importance:fixture.importance||1},null,calculateTeamOverall(opponentSquad),oppCoach):syntheticOpponentPlan(opponentClub,oppBase),oppMods=coachMatchModifiers(oppCoach),userProfile=userMods.profile,oppProfile=oppMods.profile,userMatch=tacticalMatchup(userProfile,oppProfile),oppMatch=tacticalMatchup(oppProfile,userProfile),home=fixture.home?.16:-.05,diff=(plan.lineupOverall-opponentPlan.lineupOverall)/10,userEnergy=average(plan.starters,'energy',88),userForm=average(plan.starters,'form',70),oppEnergy=average(opponentPlan.starters,'energy',91),oppForm=average(opponentPlan.starters,'form',70),fitnessEdge=((userEnergy-oppEnergy)/100)*.18+((userForm-oppForm)/100)*.10,userAttack=userMods.attackBias*.16+userMods.pressBias*.055+userMods.tempoBias*.045+userMods.possessionBias*.04+userMatch.edge,userRisk=userMods.lineRisk*.07+userMods.attackBias*.065-userProfile.pragmatism/950,oppAttack=oppMods.attackBias*.16+oppMods.pressBias*.055+oppMods.tempoBias*.045+oppMods.possessionBias*.04+oppMatch.edge,oppRisk=oppMods.lineRisk*.07+oppMods.attackBias*.065-oppProfile.pragmatism/950,xForBase=1.18+diff*.39+home+userAttack-oppRisk*.35+fitnessEdge,xAgainstBase=1.12-diff*.35-home*.42+oppAttack-userRisk*.35-fitnessEdge*.7,xFor=clamp(xForBase,.32,3.45),xAgainst=clamp(xAgainstBase,.30,3.35),seed=hash(`${save.clubId}|${fixture.id}|${save.season}|${save.matches?.length||0}|${coach.name}|${opponentClub?.id||fixture.opponentId||fixture.opponentName}`),random=rng(seed),gf=goals(xFor,random),ga=goals(xAgainst,random),control=(userMods.possessionBias-oppMods.possessionBias)*12+(plan.lineupOverall-opponentPlan.lineupOverall)*1.05+(userProfile.pressing-oppProfile.pressing)*.035,possession=clamp(Math.round(50+control+(random()-.5)*6),27,73),xg=Math.max(.2,Math.round((xFor+(random()-.5)*.24)*100)/100),xga=Math.max(.2,Math.round((xAgainst+(random()-.5)*.24)*100)/100),shots=Math.max(gf+2,Math.round(6+xg*4.6+random()*4)),shotsAgainst=Math.max(ga+2,Math.round(6+xga*4.6+random()*4)),playerGoalEvents=contributors(plan,gf,random),matchupNotes=[...userMatch.notes.slice(0,2),...oppMatch.notes.slice(0,1).map(x=>`risco: ${x}`)];return{gf,ga,possession,shots,shotsAgainst,xg,xga,teamOverall,opponentOverall:opponentPlan.lineupOverall,plan,opponentPlan,coachProfile:userProfile,opponentCoachProfile:oppProfile,playerGoalEvents,matchSeed:seed,matchupNotes}}
