import * as core from './game-v10.js';
import {state as appState} from './state.js';
import {enrichMatchManagement} from './match-management.js';
export * from './game-v10.js';
function realOpponentSquad(args){if(args?.opponentSquad?.length>=11)return args.opponentSquad;const id=String(args?.fixture?.opponentId||args?.opponentClub?.id||'');if(!id)return[];return (appState?.world?.players||[]).filter(p=>String(p.currentClubId)===id)}
function exactOpponent(args,squad){if(!squad?.length||squad.length<11)return null;const overall=core.calculateTeamOverall(squad),oppBase=Number(args?.fixture?.opponentOverall||args?.opponentClub?.teamOverall||overall||72),coach={name:args?.opponentClub?.coachName||`Técnico ${args?.fixture?.opponentName||'adversário'}`,reputation:oppBase},fixture={...(args?.fixture||{}),home:!args?.fixture?.home,opponentOverall:core.calculateTeamOverall(args?.squad||[])||72},plan=core.coachSelection(squad,fixture,null,overall,coach),starterMap=new Map((plan?.starters||[]).map(p=>[String(p.id),p])),desired=new Set(starterMap.keys()),original=new Map(squad.map(p=>[String(p.id),p]));if(desired.size<11)return null;const prepared=squad.map(p=>{const exact=starterMap.get(String(p.id)),base={...p,...(exact?{assignedSlot:exact.assignedSlot,slotKey:exact.slotKey,positionFit:exact.positionFit,positionFitLabel:exact.positionFitLabel}:{})};if(!desired.has(String(p.id)))base.overall=Math.max(35,Number(p.overall||65)-28);return base});return{plan,prepared,desired,original}}
function sameXI(plan,desired){const ids=new Set((plan?.starters||[]).map(p=>String(p.id)));return ids.size===11&&[...desired].every(id=>ids.has(id))}
function restoreOpponentPlan(result,prepared){const plan=result?.opponentPlan;if(!plan||!prepared)return;const restore=p=>{const real=prepared.original.get(String(p.id));return real?{...p,overall:Number(real.overall||p.overall),originalOverall:Number(real.overall||p.originalOverall||p.overall),marketValue:real.marketValue,position:real.position,subPosition:real.subPosition,starterPriority:real.starterPriority,realLifeStartRate:real.realLifeStartRate,realLifeStarter:real.realLifeStarter}:p};plan.starters=(plan.starters||[]).map(restore);plan.bench=(plan.bench||[]).map(restore);plan.preferredFormation=prepared.plan.preferredFormation;plan.fitAverage=prepared.plan.fitAverage;plan.selectionSource='EXACT_NATURAL_POSITION'}
export function simulateFixture(args={}){const opponentSquad=realOpponentSquad(args),prepared=exactOpponent(args,opponentSquad);let result=core.simulateFixture({...args,opponentSquad:prepared?.prepared||opponentSquad});if(prepared&&!sameXI(result?.opponentPlan,prepared.desired)){const exactOnly=(prepared.plan.starters||[]).map(p=>({...prepared.original.get(String(p.id)),assignedSlot:p.assignedSlot,slotKey:p.slotKey,positionFit:p.positionFit,positionFitLabel:p.positionFitLabel}));result=core.simulateFixture({...args,opponentSquad:exactOnly});if(result?.opponentPlan&&!(result.opponentPlan.bench||[]).length)result.opponentPlan.bench=(prepared.plan.bench||[]).map(p=>({...p}))}restoreOpponentPlan(result,prepared);result.opponentSquadSource=opponentSquad.length>=11?'REAL_DATABASE':'SYNTHETIC_FALLBACK';result.opponentSquadCount=opponentSquad.length;result.opponentExactXI=!!prepared;return enrichMatchManagement(result,args)}
