import {buildCalendar} from './game.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const PAIRS={GB1:'GB2',GB2:'GB1',ES1:'ES2',ES2:'ES1',FR1:'FR2',FR2:'FR1',IT1:'IT2',IT2:'IT1',BRA1:'BRA2',BRA2:'BRA1',SA1:'SA2',SA2:'SA1'};
const RULES={GB1:{tier:1,down:3},GB2:{tier:2,up:2,playoff:[3,4,5,6],down:3},ES1:{tier:1,down:3},ES2:{tier:2,up:2,playoff:[3,4,5,6],down:4},FR1:{tier:1,down:2,downPlayoff:1},FR2:{tier:2,up:2,playoff:[3,4,5],down:2},IT1:{tier:1,down:3},IT2:{tier:2,up:2,playoff:[3,4,5,6,7,8],down:3},BRA1:{tier:1,down:4},BRA2:{tier:2,up:4,down:4},SA1:{tier:1,down:3},SA2:{tier:2,up:2,playoff:[3,4,5,6],down:3},MLS1:{tier:1,down:0,up:0,noMovement:true},USL1:{tier:2,down:0,up:0,noMovement:true}};
const compId=club=>String(club?.competitionId||club?.domesticCompetitionId||'');
const emptyRow=club=>({clubId:String(club.id),name:club.name,ovr:club.teamOverall||72,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0});
export function ensureLeagueState(save,club,world){const cid=compId(club);if(save.leagueState?.competitionId===cid&&save.leagueState?.season===save.season)return save.leagueState;let clubs=world.clubsInCompetition(cid);if(clubs.length<4)clubs=world.clubs.filter(c=>c.league===club.league);save.leagueState={season:save.season,competitionId:cid,leagueName:club.league,round:0,table:Object.fromEntries(clubs.map(c=>[String(c.id),emptyRow(c)])),results:[]};return save.leagueState}
function addResult(row,gf,ga){row.p++;row.gf+=gf;row.ga+=ga;row.gd=row.gf-row.ga;if(gf>ga){row.w++;row.pts+=3}else if(gf===ga){row.d++;row.pts++}else row.l++}
function poisson(lambda){const L=Math.exp(-lambda);let k=0,p=1;do{k++;p*=Math.random()}while(p>L&&k<9);return k-1}
function simScore(a,b){const diff=(a.ovr-b.ovr)/12;return[poisson(clamp(1.35+diff*.35,.25,3.2)),poisson(clamp(1.2-diff*.31,.2,3))]}
export function recordLeagueMatch(save,club,fixture,gf,ga,world){if(fixture.type!=='LEAGUE')return;const s=ensureLeagueState(save,club,world),homeId=fixture.home?String(club.id):String(fixture.opponentId),awayId=fixture.home?String(fixture.opponentId):String(club.id),home=s.table[homeId],away=s.table[awayId];if(home&&away){const hg=fixture.home?gf:ga,ag=fixture.home?ga:gf;addResult(home,hg,ag);addResult(away,ag,hg);s.results.push({round:s.round+1,date:fixture.date,homeId,awayId,hg,ag,user:true})}simulateOtherMatches(save,club,world,fixture.date);s.round++}
function simulateOtherMatches(save,club,world,date){const s=ensureLeagueState(save,club,world),ids=Object.keys(s.table).filter(id=>id!==String(club.id)),shuffled=[...ids].sort(()=>Math.random()-.5);for(let i=0;i+1<shuffled.length;i+=2){const h=s.table[shuffled[i]],a=s.table[shuffled[i+1]],score=simScore(h,a);addResult(h,score[0],score[1]);addResult(a,score[1],score[0]);s.results.push({round:s.round+1,date,homeId:h.clubId,awayId:a.clubId,hg:score[0],ag:score[1],user:false})}}
export function standings(save){if(!save.leagueState)return[];return Object.values(save.leagueState.table).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||b.w-a.w||a.name.localeCompare(b.name)).map((r,i)=>({...r,pos:i+1}))}
export function userPosition(save,clubId){return standings(save).find(x=>String(x.clubId)===String(clubId))?.pos||null}
export function movementFor(save,club){const id=save.leagueState?.competitionId||compId(club),rule=RULES[id]||{tier:1,down:0},pos=userPosition(save,club.id),count=standings(save).length;if(!pos||rule.noMovement)return{type:'STAY',position:pos,targetId:null};if(rule.tier===1&&rule.down&&pos>count-rule.down)return{type:'RELEGATED',position:pos,targetId:PAIRS[id]};if(rule.tier===2){if(rule.up&&pos<=rule.up)return{type:'PROMOTED',position:pos,targetId:PAIRS[id]};if(rule.playoff?.includes(pos)){const chance=pos===3 ? .55 : pos===4 ? .42 : .28;if(Math.random()<chance)return{type:'PROMOTED_PLAYOFF',position:pos,targetId:PAIRS[id]}}}return{type:'STAY',position:pos,targetId:null}}
export function applyMovement(save,club,world,movement){if(!movement.targetId)return club;const targetClubs=world.clubsInCompetition(movement.targetId);if(!targetClubs.length)return club;const representative=targetClubs[0];save.clubOverride={...club,competitionId:movement.targetId,league:representative.league,country:representative.country||club.country};save.news.unshift({date:save.date,title:movement.type.startsWith('PROMOTED')?'PROMOVIDO!':'REBAIXADO',body:`${club.name} passa a disputar ${representative.league} na próxima temporada.`});return save.clubOverride}
export function startNewLeagueSeason(save,club,world,startDate){save.leagueState=null;ensureLeagueState(save,club,world);let rivals=world.clubsInCompetition(compId(club));if(rivals.length<4)rivals=world.clubs.filter(c=>c.league===club.league);save.calendar=buildCalendar(club,rivals,startDate);save.nextFixtureIndex=0;save.table={played:0,wins:0,draws:0,losses:0,gf:0,ga:0,points:0};save.matches=[]}
export function ruleForCompetition(id){return RULES[String(id)]||null}
