import {state,persist,squad,nextFixture,teamOverall} from './state.js';
import {coachSelection} from './game-v6.js';
import {createPresidentLineup,remapPresidentLineup,FORMATION_NAMES} from './lineup-state.js';

let installed=false,source=null;
const findSlot=(key)=>state.save?.presidentLineup?.slots?.find(s=>s.key===key);
const currentPlayers=()=>squad();
const consume=e=>{e.preventDefault?.();e.stopPropagation?.();e.stopImmediatePropagation?.()};
function previewPlan(){const players=currentPlayers(),fx=nextFixture()||{id:'plantel-preview',date:state.save?.date||'2026-08-19',opponentOverall:teamOverall(),importance:1,type:'LEAGUE',home:true};return players.length>=11?coachSelection(players,fx,nextFixture(1),teamOverall(),state.save?.coach||{}):{starters:players.slice(0,11),preferredFormation:'4-3-3'}}
function ensureManual(formation){const players=currentPlayers(),plan=previewPlan();if(!state.save.presidentLineup?.enabled)state.save.presidentLineup=createPresidentLineup(plan,players,formation);else if(formation&&state.save.presidentLineup.formation!==formation)state.save.presidentLineup=remapPresidentLineup(state.save.presidentLineup,players,formation);state.save.presidentLineup.enabled=true;return state.save.presidentLineup}
function rerender(){source=null;if(typeof window.__cdRender==='function'){window.__cdRender();return;}const nav=[...document.querySelectorAll('[data-page="squad"]')].find(x=>x.offsetParent!==null)||document.querySelector('[data-page="squad"]');if(nav)nav.click();else location.reload()}
function saveAndRender(){state.save.presidentLineup.updatedAt=new Date().toISOString();persist();rerender()}
function clearSelection(){source=null;document.querySelectorAll('.is-selected-source').forEach(x=>x.classList.remove('is-selected-source'))}
function selectSource(el,obj){clearSelection();source=obj;el.classList.add('is-selected-source');el.focus?.({preventScroll:true})}
function openPlayer(playerId){state.selectedSquadPlayerId=String(playerId);rerender()}
function slotByPlayer(playerId){return state.save.presidentLineup?.slots?.find(s=>String(s.playerId)===String(playerId))}
function placePlayerInSlot(playerId,targetKey,sourceKey=null){const o=ensureManual(),target=findSlot(targetKey);if(!target)return;const from=sourceKey?findSlot(sourceKey):slotByPlayer(playerId),oldTarget=target.playerId;target.playerId=String(playerId);if(from&&from!==target)from.playerId=oldTarget||null;else{const duplicate=o.slots.find(s=>s!==target&&String(s.playerId)===String(playerId));if(duplicate)duplicate.playerId=oldTarget||null}saveAndRender()}
function handleSlotClick(el){const key=el.dataset.lineupSlot,playerId=el.dataset.lineupPlayer||el.dataset.playerId;if(!state.save?.presidentLineup?.enabled){if(playerId)openPlayer(playerId);return}if(!source){selectSource(el,{type:'slot',key,playerId});return}if(source.type==='slot'&&source.key===key){clearSelection();return}if(source.type==='bench')placePlayerInSlot(source.playerId,key);else placePlayerInSlot(source.playerId,key,source.key)}
function handleBenchClick(el){const playerId=el.dataset.lineupBench||el.dataset.lineupPlayer;if(!state.save?.presidentLineup?.enabled){openPlayer(playerId);return}if(!source){selectSource(el,{type:'bench',playerId});return}if(source.type==='slot')placePlayerInSlot(playerId,source.key);else selectSource(el,{type:'bench',playerId})}
function handleClick(e){const edit=e.target.closest?.('[data-lineup-edit]');if(edit){consume(e);ensureManual();persist();rerender();return}const auto=e.target.closest?.('[data-lineup-auto]');if(auto){consume(e);if(state.save?.presidentLineup)state.save.presidentLineup.enabled=false;persist();rerender();return}const reset=e.target.closest?.('[data-lineup-reset]');if(reset){consume(e);state.save.presidentLineup=createPresidentLineup(previewPlan(),currentPlayers(),state.save.presidentLineup?.formation);persist();rerender();return}const slot=e.target.closest?.('[data-lineup-slot]');if(slot){consume(e);handleSlotClick(slot);return}const bench=e.target.closest?.('[data-lineup-bench]');if(bench){consume(e);handleBenchClick(bench);return}}
function handleChange(e){if(e.target?.id!=='lineupFormation')return;const formation=e.target.value;if(!FORMATION_NAMES.includes(formation))return;consume(e);ensureManual(formation);persist();rerender()}
function handleDragStart(e){const el=e.target.closest?.('[data-lineup-player]');if(!el||!state.save?.presidentLineup?.enabled)return;const playerId=el.dataset.lineupPlayer,sourceKey=el.dataset.lineupSlot||'';source={type:sourceKey?'slot':'bench',key:sourceKey||null,playerId};el.classList.add('is-selected-source');try{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',JSON.stringify({playerId,sourceKey}))}catch{}}
function handleDragEnd(){document.querySelectorAll('.is-selected-source').forEach(x=>x.classList.remove('is-selected-source'));source=null}
function handleDragOver(e){if(e.target.closest?.('[data-lineup-slot]')&&state.save?.presidentLineup?.enabled){e.preventDefault();try{e.dataTransfer.dropEffect='move'}catch{}}}
function handleDrop(e){const target=e.target.closest?.('[data-lineup-slot]');if(!target||!state.save?.presidentLineup?.enabled)return;consume(e);let data=null;try{data=JSON.parse(e.dataTransfer.getData('text/plain'))}catch{};const playerId=data?.playerId||source?.playerId,sourceKey=data?.sourceKey||source?.key||null;if(playerId)placePlayerInSlot(playerId,target.dataset.lineupSlot,sourceKey)}
export function installLineupActions(){if(installed)return;installed=true;document.addEventListener('click',handleClick,true);document.addEventListener('change',handleChange,true);document.addEventListener('dragstart',handleDragStart,true);document.addEventListener('dragend',handleDragEnd,true);document.addEventListener('dragover',handleDragOver,true);document.addEventListener('drop',handleDrop,true)}
