import {state,esc,ownedIds,soldIds,formatCurrency,formatDate,contractLabel,normalizedName,currentClub,gameDate} from './state.js';
import {askingPrice} from './game.js';
import {transferWindow} from './transfer-engine.js';
import {loadingPlayers,noPlayers,ratingClass} from './views.js';
import {playerPhoto} from './media.js';

export function marketPage(){
  if(state.playersLoading)return `<div class="hero"><div><h1>Mercado</h1><p>Carregando jogadores e imagens…</p></div></div>${loadingPlayers()}`;
  if(!state.playersReady||!state.world.players?.length)return `<div class="hero"><div><h1>Mercado</h1></div></div>${noPlayers()}`;
  const all=state.world.marketPlayers(state.save.clubId,ownedIds(),soldIds()),p=all.find(x=>String(x.id)===String(state.selectedMarketPlayerId)),win=transferWindow(currentClub()?.country,gameDate());
  return `<div class="hero"><div><span class="eyebrow">MERCADO MUNDIAL</span><h1>Contratações</h1><p>${all.length.toLocaleString('pt-BR')} jogadores de outros clubes. Seus atletas não aparecem como alvos.</p></div><div><span class="subtle">${win.open?'JANELA ABERTA':'FORA DA JANELA'}</span><div class="metric money">${formatCurrency(state.save.transferBudget)}</div></div></div><div class="market-toolbar card advanced"><input id="marketSearch" placeholder="Jogador, clube ou nacionalidade"><select id="marketPosition"><option value="">Posição</option><option>Goalkeeper</option><option>Defence</option><option>Midfield</option><option>Attack</option></select><select id="marketOvr"><option value="0">OVR</option><option value="85">85+</option><option value="80">80+</option><option value="75">75+</option><option value="70">70+</option></select><input id="marketAge" type="number" min="15" max="45" placeholder="Idade máx."><input id="marketValue" type="number" min="0" placeholder="Valor máx. €"><button class="button secondary" id="marketFilter">Filtrar</button></div><div id="marketResults">${marketResults(all,'','',0,null,null)}</div>${p?`<div class="modal-backdrop" id="marketModal"><div class="transfer-modal card">${panel(p,win.open)}</div></div>`:''}`;
}

export function marketResults(all,search,position,minOvr,maxAge=null,maxValue=null){
  const q=normalizedName(search),filtered=all.filter(p=>(!q||normalizedName(`${p.name} ${p.currentClubName} ${p.nationality}`).includes(q))&&(!position||p.position===position)&&p.overall>=minOvr&&(!maxAge||(p.age??99)<=maxAge)&&(!maxValue||(p.marketValue||0)<=maxValue)).sort((a,b)=>(b.overall||0)-(a.overall||0)||(b.marketValue||0)-(a.marketValue||0));
  const size=60,pages=Math.max(1,Math.ceil(filtered.length/size));state.marketPageIndex=Math.max(0,Math.min(state.marketPageIndex,pages-1));const list=filtered.slice(state.marketPageIndex*size,(state.marketPageIndex+1)*size);
  return `<div class="table-wrap"><table><thead><tr><th>Jogador</th><th>Clube</th><th>Posição</th><th>Idade</th><th>OVR</th><th>POT</th><th>Contrato</th><th>Valor</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><div class="fp-player-cell">${playerPhoto(p,{size:'sm'})}<div><b>${esc(p.name)}</b><small>${esc(p.nationality||'')}</small></div></div></td><td>${esc(p.currentClubName||'—')}</td><td>${esc(p.subPosition||p.position)}</td><td>${p.age??'—'}</td><td><b class="rating ${ratingClass(p.overall)}">${p.overall}</b></td><td>${p.potential}</td><td>${contractLabel(p.contractExpiration)}<small>${formatDate(p.contractExpiration)}</small></td><td>${p.marketValue?formatCurrency(p.marketValue):'—'}</td><td><button class="button secondary compact" data-market-player="${esc(p.id)}">Negociar</button></td></tr>`).join('')}</tbody></table></div><div class="pagination"><button class="button ghost compact" id="prevMarket" ${state.marketPageIndex<=0?'disabled':''}>←</button><span>Página ${state.marketPageIndex+1}/${pages} • ${filtered.length.toLocaleString('pt-BR')}</span><button class="button ghost compact" id="nextMarket" ${state.marketPageIndex>=pages-1?'disabled':''}>→</button></div>`;
}

function panel(p,open){
  const ask=askingPrice(p);
  return `<button class="modal-close" id="closeMarket">×</button><span class="eyebrow">NEGOCIAÇÃO • ${open?'JANELA ABERTA':'ACORDO PARA PRÓXIMA JANELA'}</span><div class="player-head">${playerPhoto(p,{size:'xl'})}<div><h2>${esc(p.name)}</h2><p>${esc(p.currentClubName)} • ${esc(p.subPosition||p.position)}</p><small class="subtle">${esc(p.nationality||'')} • ${p.age??'—'} anos</small></div><b class="rating huge ${ratingClass(p.overall)}">${p.overall}</b></div><div class="grid grid-3 mini-stats"><div><span>Valor</span><b>${formatCurrency(p.marketValue)}</b></div><div><span>Contrato</span><b>${contractLabel(p.contractExpiration)}</b><small>${formatDate(p.contractExpiration)}</small></div><div><span>Potencial</span><b>${p.potential}</b></div></div><div class="negotiation-tabs"><button class="active" data-offer-mode="BUY">Compra</button><button data-offer-mode="LOAN">Empréstimo</button></div><div id="buyOffer"><div class="grid grid-2"><div class="offer-box"><label>À vista</label><input id="offerValue" type="number" value="${ask}" step="100000"></div><div class="offer-box"><label>Parcelado adicional</label><input id="installmentValue" type="number" value="0" step="100000"></div><div class="offer-box"><label>Parcelas semestrais</label><input id="installmentCount" type="number" min="0" max="6" value="0"></div><div class="offer-box"><label>% venda futura</label><input id="sellOn" type="number" min="0" max="50" value="0"></div><div class="offer-box"><label>Bônus por jogos</label><input id="appearanceBonus" type="number" min="0" value="0"></div><div class="offer-box"><label>Bônus por título</label><input id="titleBonus" type="number" min="0" value="0"></div></div><small>Pedido aproximado: ${formatCurrency(ask)}</small><button class="button big full" id="sendOffer">Enviar proposta de compra</button></div><div id="loanOffer" hidden><div class="grid grid-2"><div class="offer-box"><label>Duração (meses)</label><input id="loanMonths" type="number" min="1" max="24" value="12"></div><div class="offer-box"><label>Taxa</label><input id="loanFee" type="number" min="0" value="0"></div><div class="offer-box"><label>% salário pago</label><input id="wageShare" type="number" min="0" max="100" value="100"></div><div class="offer-box"><label>Opção de compra</label><input id="buyOption" type="number" min="0" value="0"></div></div><button class="button big full" id="sendLoan">Propor empréstimo</button></div><div id="offerFeedback"></div>`;
}
