const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=str=>[...String(str)].reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,2166136261)>>>0;
function rng(seed){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function role(p){const x=`${p?.position||''} ${p?.subPosition||''} ${p?.assignedSlot||''}`.toLowerCase();if(/goal|keeper|gole|^gk/.test(x))return'GK';if(/defen|back|zague|lateral|\bcb\b|\blb\b|\brb\b/.test(x))return'DEF';if(/mid|meia|medio|volante|wing-back|\bcm\b|\bdm\b|\bam\b/.test(x))return'MID';return'ATT'}
function weightedPick(list,weight,random){if(!list?.length)return null;const weights=list.map(x=>Math.max(.01,weight(x))),sum=weights.reduce((a,b)=>a+b,0);let r=random()*sum;for(let i=0;i<list.length;i++){r-=weights[i];if(r<=0)return list[i]}return list.at(-1)}
function actorWeight(p){return role(p)==='ATT'?5.5:role(p)==='MID'?2.8:role(p)==='DEF'?.7:.08}
function passWeight(p){return role(p)==='MID'?4.4:role(p)==='ATT'?2.6:role(p)==='DEF'?1.7:.25}
function safePlan(plan={}){return{...plan,starters:plan.starters||[],bench:plan.bench||[],coachProfile:plan.coachProfile||{}}}
function allParticipants(plan){const starters=plan.starters||[],entered=(plan.bench||[]).filter(p=>Number(p.subMinute)>0);return[...starters,...entered]}
function playerById(plan,id){return allParticipants(plan).find(p=>String(p.id)===String(id))||null}
function minutePicker(random){const used=new Map();return(preferred=null)=>{let m=preferred==null?Math.floor(2+random()*87):clamp(Math.round(preferred),1,90);for(let tries=0;tries<12;tries++){const n=used.get(m)||0;if(n<2){used.set(m,n+1);return m}m=m>=89?2:m+1}return m}}
function chooseScorer(plan,random){return weightedPick(plan.starters,actorWeight,random)||plan.starters[0]||null}
function chooseAssist(plan,scorer,random){const pool=plan.starters.filter(p=>String(p.id)!==String(scorer?.id));return random()<.72?weightedPick(pool,passWeight,random):null}
function sequenceFor(plan,shooter,random){const active=plan.starters.filter(Boolean),seq=[],used=new Set();const desired=3+Math.floor(random()*3);let current=weightedPick(active,p=>role(p)==='DEF'?3:role(p)==='MID'?2:1,random)||active[0];for(let i=0;i<desired-1&&current;i++){if(!used.has(String(current.id))){seq.push({id:String(current.id),name:current.name,role:role(current)});used.add(String(current.id))}const pool=active.filter(p=>!used.has(String(p.id))&&String(p.id)!==String(shooter?.id));current=weightedPick(pool,passWeight,random)}if(shooter)seq.push({id:String(shooter.id),name:shooter.name,role:role(shooter)});return seq}
function calcSideStats({shots,goals,xg,possession,profile,random}){const onTarget=clamp(goals+Math.round(Math.max(0,shots-goals)*(.28+random()*.13)),goals,shots),direct=Number(profile?.directness||52),press=Number(profile?.pressing||55),tempo=Number(profile?.tempo||58),possBias=Number(profile?.possessionBias||52),corners=clamp(Math.round((shots-goals)*.28+random()*2.8),0,13),fouls=clamp(Math.round(7+press*.075+random()*4.5),6,22),offsides=clamp(Math.round(.5+direct*.018+random()*2.3),0,6),passes=clamp(Math.round(245+possession*4.4+(possBias-50)*2.2-(direct-50)*1.1+random()*32),240,760),passPct=clamp(Math.round(79+(possession-50)*.11+(possBias-50)*.09-(direct-50)*.06+(random()-.5)*3),67,94),completed=Math.round(passes*passPct/100),tackles=clamp(Math.round(11+(100-possession)*.12+press*.05+random()*4),8,27),bigChances=clamp(Math.max(goals,Math.round(xg*.72+random()*1.5)),goals,8);return{shots,onTarget,goals,xg:Number(xg||0),possession,corners,fouls,offsides,passes,completed,passPct,tackles,bigChances}}
function distributeXg(events,total,random){const shots=events.filter(e=>['GOAL','SHOT_ON','SHOT_OFF'].includes(e.type));if(!shots.length)return;const weights=shots.map(e=>e.type==='GOAL'?.24+random()*.35:e.type==='SHOT_ON'?.08+random()*.22:.02+random()*.12),sum=weights.reduce((a,b)=>a+b,0)||1;let used=0;shots.forEach((e,i)=>{const value=i===shots.length-1?Math.max(.01,total-used):Math.max(.01,weights[i]/sum*total);e.xg=Math.round(value*100)/100;used+=e.xg});const rounded=shots.reduce((s,e)=>s+e.xg,0),diff=Math.round((total-rounded)*100)/100;if(Math.abs(diff)>=.01){shots[0].xg=Math.max(.01,Math.round((shots[0].xg+diff)*100)/100)}}
function eventText(type,teamLabel,actor,assist){const name=actor?.name||teamLabel;switch(type){case'GOAL':return assist?`GOOOL! ${name} finaliza após passe de ${assist.name}.`:`GOOOL! ${name} marca.`;case'SHOT_ON':return`${name} finaliza e o goleiro faz a defesa.`;case'SHOT_OFF':return`${name} arrisca, mas a bola sai.`;case'CORNER':return`Escanteio para ${teamLabel}.`;case'FOUL':return`Falta cometida por ${name}.`;case'CARD':return`Cartão amarelo para ${name}.`;case'OFFSIDE':return`Impedimento de ${name}.`;default:return`${teamLabel} trabalha a posse.`}}
function buildSideEvents({team,teamLabel,plan,stats,goalsData,random,pickMinute}){const out=[];let goalIndex=0;const goalActors=[];for(let i=0;i<stats.goals;i++){const registered=goalsData?.[i],scorer=registered?playerById(plan,registered.scorerId)||plan.starters.find(p=>p.name===registered.scorer):chooseScorer(plan,random),assist=registered?.assistId?playerById(plan,registered.assistId):registered?.assist?plan.starters.find(p=>p.name===registered.assist):chooseAssist(plan,scorer,random);goalActors.push({scorer,assist})}
 const nonGoalOn=Math.max(0,stats.onTarget-stats.goals),off=Math.max(0,stats.shots-stats.onTarget),shotKinds=[...Array(stats.goals).fill('GOAL'),...Array(nonGoalOn).fill('SHOT_ON'),...Array(off).fill('SHOT_OFF')];
 for(let i=shotKinds.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[shotKinds[i],shotKinds[j]]=[shotKinds[j],shotKinds[i]]}
 for(const type of shotKinds){let scorer=null,assist=null;if(type==='GOAL'){const g=goalActors[goalIndex++]||{};scorer=g.scorer;assist=g.assist}else scorer=chooseScorer(plan,random);const minute=pickMinute(),zone=['LEFT','CENTER','RIGHT'][Math.floor(random()*3)];out.push({minute,type,team,playerId:scorer?String(scorer.id):null,playerName:scorer?.name||'',assistId:assist?String(assist.id):null,assistName:assist?.name||'',zone,sequence:sequenceFor(plan,scorer,random),text:eventText(type,teamLabel,scorer,assist)})}
 for(let i=0;i<stats.corners;i++)out.push({minute:pickMinute(),type:'CORNER',team,zone:random()<.5?'LEFT':'RIGHT',text:eventText('CORNER',teamLabel)});
 const cards=clamp(Math.round(stats.fouls*.08+random()*1.4),0,4),foulActors=[];for(let i=0;i<stats.fouls;i++){const actor=weightedPick(plan.starters,p=>role(p)==='DEF'?3:role(p)==='MID'?2:1,random);foulActors.push(actor);out.push({minute:pickMinute(),type:'FOUL',team,playerId:actor?String(actor.id):null,playerName:actor?.name||'',text:eventText('FOUL',teamLabel,actor)})}
 for(let i=0;i<cards;i++){const actor=foulActors[Math.floor(random()*Math.max(1,foulActors.length))]||plan.starters[i%Math.max(1,plan.starters.length)];out.push({minute:pickMinute(),type:'CARD',team,playerId:actor?String(actor.id):null,playerName:actor?.name||'',text:eventText('CARD',teamLabel,actor)})}
 for(let i=0;i<stats.offsides;i++){const actor=weightedPick(plan.starters,p=>role(p)==='ATT'?4:role(p)==='MID'?1.5:.4,random);out.push({minute:pickMinute(),type:'OFFSIDE',team,playerId:actor?String(actor.id):null,playerName:actor?.name||'',text:eventText('OFFSIDE',teamLabel,actor)})}
 return out}
function addSubs(out,team,subs=[]){for(const s of subs)out.push({minute:Number(s.minute)||65,type:'SUB',team,outId:String(s.outId||''),outName:s.outName||'',inId:String(s.inId||''),inName:s.inName||'',text:`${s.outName} sai, ${s.inName} entra. ${s.reason||'Ajuste do treinador'}.`})}
function ratingRows(plan,timeline,team,result,random){const goals=new Map(),assists=new Map(),cards=new Set();timeline.filter(e=>e.team===team).forEach(e=>{if(e.type==='GOAL'&&e.playerId)goals.set(e.playerId,(goals.get(e.playerId)||0)+1);if(e.type==='GOAL'&&e.assistId)assists.set(e.assistId,(assists.get(e.assistId)||0)+1);if(e.type==='CARD'&&e.playerId)cards.add(e.playerId)});const won=team==='USER'?result.gf>result.ga:result.ga>result.gf,draw=result.gf===result.ga,clean=team==='USER'?result.ga===0:result.gf===0;return allParticipants(plan).map(p=>{const starter=plan.starters.some(x=>String(x.id)===String(p.id)),minutes=starter?clamp(Number(p.replacedAt||90),1,90):clamp(90-Number(p.subMinute||90),1,38),g=goals.get(String(p.id))||0,a=assists.get(String(p.id))||0,r=role(p);let value=6.15+(won?.32:draw?.06:-.22)+(Number(p.overall||70)-70)*.008+g*.82+a*.38+(clean&&(r==='GK'||r==='DEF')?.35:0)-(cards.has(String(p.id))?.18:0)+(minutes<25?.03:0)+(random()-.5)*.26;if(Number(p.positionFit||1)<.9)value-=.22;value=clamp(Math.round(value*10)/10,4.8,10);return{id:String(p.id),name:p.name,rating:value,minutes,goals:g,assists:a,position:p.assignedSlot||p.subPosition||p.position||'',overall:p.originalOverall||p.overall||0,image:p.image||p.imageUrl||'',starter}}).sort((a,b)=>b.rating-a.rating)}
function momentumSeries(timeline,result,random){const out=[],base=(Number(result.possession||50)-50)*.7+(Number(result.xg||0)-Number(result.xga||0))*5;for(let start=0;start<90;start+=5){const end=start+5,events=timeline.filter(e=>e.minute>start&&e.minute<=end),impact=events.reduce((s,e)=>s+(e.team==='USER'?1:-1)*(e.type==='GOAL'?26:e.type==='SHOT_ON'?9:e.type==='SHOT_OFF'?4:e.type==='CORNER'?3:e.type==='CARD'?-4:0),0),value=clamp(Math.round(base+impact+(random()-.5)*28),-100,100);out.push({minute:end,value})}return out}
export function enrichMatchResult(result,args={}){const fixture=args.fixture||{},userPlan=safePlan(result.plan),oppPlan=safePlan(result.opponentPlan),seed=(Number(result.matchSeed)||hash(`${fixture.id}|${fixture.date}`))^0x51f2e7a9,random=rng(seed),pickMinute=minutePicker(random),userStats=calcSideStats({shots:Number(result.shots||0),goals:Number(result.gf||0),xg:Number(result.xg||0),possession:Number(result.possession||50),profile:userPlan.coachProfile,random}),oppStats=calcSideStats({shots:Number(result.shotsAgainst||0),goals:Number(result.ga||0),xg:Number(result.xga||0),possession:100-Number(result.possession||50),profile:oppPlan.coachProfile,random});userStats.saves=Math.max(0,oppStats.onTarget-oppStats.goals);oppStats.saves=Math.max(0,userStats.onTarget-userStats.goals);
 const userLabel=args.save?.clubName||args.save?.clubSnapshot?.name||'Seu clube',oppLabel=fixture.opponentName||'Adversário',timeline=[...buildSideEvents({team:'USER',teamLabel:userLabel,plan:userPlan,stats:userStats,goalsData:result.playerGoalEvents||[],random,pickMinute}),...buildSideEvents({team:'OPPONENT',teamLabel:oppLabel,plan:oppPlan,stats:oppStats,goalsData:null,random,pickMinute})];addSubs(timeline,'USER',result.substitutions||[]);addSubs(timeline,'OPPONENT',result.opponentSubstitutions||[]);timeline.push({minute:45,type:'HALF',team:null,text:'Intervalo.'},{minute:90,type:'FULL',team:null,text:'Fim de jogo.'});timeline.sort((a,b)=>a.minute-b.minute||(['GOAL','SHOT_ON','SHOT_OFF','CARD','SUB','CORNER','FOUL','OFFSIDE','HALF','FULL'].indexOf(a.type)-['GOAL','SHOT_ON','SHOT_OFF','CARD','SUB','CORNER','FOUL','OFFSIDE','HALF','FULL'].indexOf(b.type)));distributeXg(timeline.filter(e=>e.team==='USER'),userStats.xg,random);distributeXg(timeline.filter(e=>e.team==='OPPONENT'),oppStats.xg,random);
 result.detailedStats={user:userStats,opponent:oppStats};result.timeline=timeline;result.playerRatings=ratingRows(userPlan,timeline,'USER',result,random);result.opponentPlayerRatings=ratingRows(oppPlan,timeline,'OPPONENT',result,random);result.bestPlayer=[...result.playerRatings.map(x=>({...x,team:'USER'})),...result.opponentPlayerRatings.map(x=>({...x,team:'OPPONENT'}))].sort((a,b)=>b.rating-a.rating)[0]||null;result.momentum=momentumSeries(timeline,result,random);result.matchModelVersion=7;return result}
