import {state,esc,formatDate} from './state.js';
import {daysUntil,injuryStage} from './injury-engine.js';
function injuries(save=state.save){const rows=[];for(const [id,s] of Object.entries(save?.playerCareer||{})){if(!s?.injuryUntil||s.injuryUntil<=save.date)continue;const p=state.world?.players?.find(x=>String(x.id)===String(id)),d=s.injuryDetail||{};rows.push({id:`inj-${id}`,kind:'MEDICAL',priority:d.severity==='GRAVE'?'HIGH':'NORMAL',title:`${p?.name||'Jogador'} no departamento médico`,body:`${d.name||'Lesão'} • ${injuryStage(d,save.date)||'TRATAMENTO'} • ${daysUntil(save.date,s.injuryUntil)} dia(s) para o retorno`,date:d.occurredOn||save.date,playerId:id})}return rows}
function transfers(save=state.save){return(save?.transferInbox||[]).filter(x=>x.status==='PENDING').map(o=>({id:`offer-${o.id}`,kind:'MARKET',priority:'HIGH',title:`Proposta por ${o.playerName}`,body:`${o.buyerName} aguarda sua resposta • ${o.type==='LOAN'?'empréstimo':'compra'}`,date:o.date||save.date,page:'inbox'}))}
function demands(save=state.save){return(save?.playerDemands||[]).filter(x=>['PENDING','ACKNOWLEDGED'].includes(x.status)).map(d=>({id:`d-${d.id}`,kind:'CONTRACT',priority:d.priority||'NORMAL',title:`${d.playerName} quer conversar`,body:d.message,date:d.date,playerId:d.playerId}))}
function decisions(save=state.save){return(save?.pendingDecisions||[]).map((d,i)=>({id:`decision-${d.id||i}`,kind:'BOARD',priority:'HIGH',title:d.title||'Decisão pendente',body:d.body||d.message||'A diretoria aguarda uma decisão.',date:d.date||save.date,page:'dashboard'}))}
export function activeNotifications(save=state.save){return[...injuries(save),...transfers(save),...demands(save),...decisions(save)].sort((a,b)=>(a.priority==='HIGH'?-1:0)-(b.priority==='HIGH'?-1:0)||String(b.date).localeCompare(String(a.date)))}
export function notificationCount(save=state.save){return activeNotifications(save).length}
const icon=k=>k==='MEDICAL'?'✚':k==='MARKET'?'⇄':k==='CONTRACT'?'✎':'!';
const label=k=>k==='MEDICAL'?'Departamento médico':k==='MARKET'?'Mercado':k==='CONTRACT'?'Contratos':'Diretoria';
export function notificationsPage(){const all=activeNotifications(),filter=state.notificationFilter||'ALL',items=filter==='ALL'?all:all.filter(x=>x.kind===filter),medical=all.filter(x=>x.kind==='MEDICAL').length,market=all.filter(x=>x.kind==='MARKET').length,contracts=all.filter(x=>x.kind==='CONTRACT').length;return `<section class="gcp-notifications"><div class="hero gcp-notification-head"><div><span class="eyebrow">CENTRAL DO CLUBE</span><h1>Notificações</h1><p>Lesões, propostas, contratos e decisões que precisam da sua atenção.</p></div><div class="gcp-notif-kpis"><span><b>${medical}</b> DM</span><span><b>${market}</b> mercado</span><span><b>${contracts}</b> contratos</span></div></div><div class="gcp-notif-tabs card">${[['ALL','Tudo'],['MEDICAL','Lesões'],['MARKET','Mercado'],['CONTRACT','Contratos'],['BOARD','Diretoria']].map(([id,n])=>`<button data-notification-filter="${id}" class="${filter===id?'active':''}">${n}</button>`).join('')}</div><div class="gcp-notif-list">${items.map(n=>`<button class="card gcp-notif-item ${n.priority==='HIGH'?'urgent':''}" ${n.playerId?`data-notification-player="${esc(n.playerId)}"`:`data-notification-page="${n.page||'dashboard'}"`}><i>${icon(n.kind)}</i><span><small>${label(n.kind)} • ${formatDate(n.date)}</small><b>${esc(n.title)}</b><em>${esc(n.body)}</em></span><strong>›</strong></button>`).join('')||`<div class="card gcp-notif-empty"><b>Tudo tranquilo.</b><span>Não há nenhuma pendência nesta categoria.</span></div>`}</div></section>`}
export function bindNotifications(render){document.querySelectorAll('[data-notification-filter]').forEach(b=>b.onclick=()=>{state.notificationFilter=b.dataset.notificationFilter;render()});document.querySelectorAll('[data-notification-player]').forEach(b=>b.onclick=()=>{state.selectedSquadPlayerId=b.dataset.notificationPlayer;state.page='squad';render()});document.querySelectorAll('[data-notification-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.notificationPage;render()})}
