import {coachGameplayProfile} from './coach-profile.js';
import {simulateWorldTick,ensureWorldSimulation} from './world-sim.js';
import {processPlayerDynamics} from './player-dynamics.js';
const DAY=86400000,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const addDays=(date,days)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
const daysBetween=(a,b)=>Math.floor((new Date(`${b}T12:00:00Z`)-new Date(`${a}T12:00:00Z`))/DAY);
const id=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const SCOUT_SPECIALTIES=[
 {id:'YOUTH',label:'Jovens e potencial',positions:[],ageBonus:21},
 {id:'ATTACK',label:'Atacantes',positions:['Attack']},
 {id:'MIDFIELD',label:'Meio-campo',positions:['Midfield']},
 {id:'DEFENCE',label:'Defensores',positions:['Defence']},
 {id:'VALUE',label:'Oportunidades de mercado',positions:[]},
 {id:'FIRST_TEAM',label:'Prontos para o primeiro time',positions:[]}
];
export function ensurePlan2(save){if(!save)return save;save.scouting??={assignments:[],reports:[],shortlist:[]};save.transferInbox??=[];save.transferListed??=[];save.loanListed??=[];save.negotiationHistory??=[];save.staff??={sportingDirector:null,directorAutonomy:'LOW',transferAuthority:'PRESIDENT',scouts:[],medicalLevel:5};save.staff.scouts??=[];return save}
export const scoutTiers={regional:{label:'Scout regional',quality:58,cost:180000},national:{label:'Scout nacional',quality:72,cost:420000},elite:{label:'Scout internacional',quality:86,cost:850000}};
function scoutSpecialtyFor(index,tier){const offset=tier==='elite'?2:tier==='national'?1:0;return SCOUT_SPECIALTIES[(index+offset)%SCOUT_SPECIALTIES.length]}
export function hireScout(save,tier='regional',date='2026-08-14'){ensurePlan2(save);const t=scoutTiers[tier]||scoutTiers.regional;if(save.staff.scouts.length>=8)return{ok:false,message:'A rede já tem 8 scouts.'};if((save.cash||0)<t.cost)return{ok:false,message:'Caixa insuficiente para contratar este scout.'};const n=save.staff.scouts.length+1,spec=scoutSpecialtyFor(n-1,tier),scout={id:id('scout'),name:`Scout ${n}`,role:t.label,quality:t.quality+Math.floor(Math.random()*7)-3,tier,joined:date,assignmentId:null,specialty:spec.id,specialtyLabel:spec.label,negotiationInsight:clamp(t.quality+Math.floor(Math.random()*9)-4,45,94),adaptability:clamp(t.quality-8+Math.floor(Math.random()*18),40,94)};save.staff.scouts.push(scout);save.cash-=t.cost;save.transactions?.push({date,type:'Scouting',description:`Contratação: ${t.label} • ${spec.label}`,amount:-t.cost});return{ok:true,scout}}
export function fireScout(save,scoutId){ensurePlan2(save);const scout=save.staff.scouts.find(s=>String(s.id)===String(scoutId));if(!scout)return false;if(scout.assignmentId){const a=save.scouting.assignments.find(x=>x.id===scout.assignmentId);if(a)a.status='CANCELLED'}save.staff.scouts=save.staff.scouts.filter(s=>String(s.id)!==String(scoutId));return true}
export function startScoutAssignment(save,{scoutId,country='',competitionId='',position='',maxAge=99,days=14},date){ensurePlan2(save);const scout=save.staff.scouts.find(s=>String(s.id)===String(scoutId));if(!scout)return{ok:false,message:'Selecione um scout.'};if(scout.assignmentId)return{ok:false,message:'Este scout já está em missão.'};const duration=clamp(Number(days)||14,7,45),assignment={id:id('mission'),scoutId:scout.id,scoutName:scout.name,country,competitionId,position,maxAge:Number(maxAge)||99,start:date,due:addDays(date,duration),status:'ACTIVE'};save.scouting.assignments.unshift(assignment);scout.assignmentId=assignment.id;return{ok:true,assignment}}
function group(p){const x=`${p.position||''} ${p.subPosition||''}`.toLowerCase();if(/goal|keeper/.test(x))return'Goalkeeper';if(/defen|back/.test(x))return'Defence';if(/mid|wing/.test(x))return'Midfield';return'Attack'}
function specialtyBonus(scout,player){const g=group(player),spec=scout?.specialty;if(spec==='YOUTH'&&(player.age||99)<=21)return 11;if(spec==='ATTACK'&&g==='Attack')return 10;if(spec==='MIDFIELD'&&g==='Midfield')return 10;if(spec==='DEFENCE'&&g==='Defence')return 10;if(spec==='VALUE'&&(player.marketValue||0)<Math.max(2e6,(player.overall||65)*180000))return 9;if(spec==='FIRST_TEAM'&&(player.overall||0)>=78)return 9;return 0}
function tacticalFit(player,profile){let fit=58+(player.overall||65)*.18;const g=group(player),sub=String(player.subPosition||'').toLowerCase();if(profile.pressing>=70&&(player.age||30)<=27)fit+=7;if(profile.width>=68&&/wing|left|right|back/.test(sub))fit+=8;if(profile.possessionBias>=70&&g==='Midfield')fit+=7;if(profile.directness>=70&&g==='Attack')fit+=6;if(profile.youthDevelopment>=70&&(player.age||99)<=21)fit+=7;if(profile.pragmatism>=72&&g==='Defence')fit+=5;return clamp(Math.round(fit),45,96)}
function recommendation(player,fit){if(fit>=87&&player.overall>=80)return'Prioridade';if(fit>=80)return'Recomendado';if((player.potential||0)>=(player.overall||0)+5)return'Projeto de futuro';if(fit<66)return'Encaixe baixo';return'Observar'}
function marketVerdict(player,quality){const value=player.marketValue||0,ovr=player.overall||65,benchmark=Math.max(500000,Math.pow(Math.max(1,ovr-55),2)*115000);const ratio=value/benchmark;if(ratio<.62)return'Oportunidade';if(ratio>1.65)return'Preço alto';return quality>=78?'Preço aceitável':'Valor incerto'}
export function processScouting(save,world,date){ensurePlan2(save);if(!world?.players?.length)return[];const done=[];for(const a of save.scouting.assignments.filter(x=>x.status==='ACTIVE'&&x.due<=date)){const scout=save.staff.scouts.find(s=>String(s.id)===String(a.scoutId)),profile=coachGameplayProfile(save.coach||{}),clubs=new Map((world.clubs||[]).map(c=>[String(c.id),c]));let pool=world.players.filter(p=>String(p.currentClubId)!==String(save.clubId)&&(p.age??99)<=a.maxAge);if(a.position)pool=pool.filter(p=>group(p)===a.position);if(a.competitionId)pool=pool.filter(p=>String(p.competitionId||clubs.get(String(p.currentClubId))?.competitionId||'')===String(a.competitionId));if(a.country)pool=pool.filter(p=>(clubs.get(String(p.currentClubId))?.country||p.nationality||'')===a.country);pool=pool.sort((x,y)=>((y.potential||y.overall||0)+(y.overall||0)+specialtyBonus(scout,y))-((x.potential||x.overall||0)+(x.overall||0)+specialtyBonus(scout,x))).slice(0,Math.max(5,Math.round((scout?.quality||55)/7)));for(const p of pool){const spec=specialtyBonus(scout,p),effectiveQuality=clamp((scout?.quality||55)+spec,45,98),uncertainty=Math.max(1,Math.round((100-effectiveQuality)/14)),fit=tacticalFit(p,profile),risk=effectiveQuality>=86?'Baixo':effectiveQuality>=70?'Médio':'Alto';save.scouting.reports.unshift({id:id('report'),playerId:String(p.id),playerName:p.name,clubName:p.currentClubName||'',date,scoutId:a.scoutId,scoutName:a.scoutName,quality:effectiveQuality,scoutSpecialty:scout?.specialtyLabel||'',overallLow:Math.max(45,(p.overall||65)-uncertainty),overallHigh:Math.min(99,(p.overall||65)+uncertainty),potentialLow:Math.max(45,(p.potential||p.overall||65)-uncertainty),potentialHigh:Math.min(99,(p.potential||p.overall||65)+uncertainty),tacticalFit:fit,recommendation:recommendation(p,fit),marketValue:p.marketValue||0,marketVerdict:marketVerdict(p,effectiveQuality),confidence:effectiveQuality,risk,position:p.subPosition||p.position,age:p.age})}a.status='DONE';a.completed=date;if(scout)scout.assignmentId=null;done.push(a)}save.scouting.reports=save.scouting.reports.slice(0,250);return done}
export function toggleShortlist(save,playerId){ensurePlan2(save);const id=String(playerId),has=save.scouting.shortlist.some(x=>String(x)===id);save.scouting.shortlist=has?save.scouting.shortlist.filter(x=>String(x)!==id):[id,...save.scouting.shortlist];return!has}
function chooseOwnPlayer(save,world){const out=new Set((save.loans||[]).filter(l=>l.active&&l.direction==='OUT').map(l=>String(l.playerId))),owned=new Set((save.acquiredPlayerIds||[]).map(String));let players=(world.players||[]).filter(p=>(String(p.currentClubId)===String(save.clubId)||owned.has(String(p.id)))&&!out.has(String(p.id))&&!(save.soldPlayerIds||[]).includes(String(p.id)));const listed=new Set([...(save.transferListed||[]),...(save.loanListed||[])].map(String));players=players.filter(p=>(p.marketValue||0)>250000).sort((a,b)=>(listed.has(String(b.id))?1:0)-(listed.has(String(a.id))?1:0)||(b.marketValue||0)-(a.marketValue||0));if(!players.length)return null;const top=players.slice(0,Math.min(14,players.length));return top[Math.floor(Math.random()*top.length)]}
function squadNeed(world,club,position){const squad=(world.players||[]).filter(p=>String(p.currentClubId)===String(club.id)),counts={Goalkeeper:0,Defence:0,Midfield:0,Attack:0};squad.forEach(p=>counts[group(p)]++);const targets={Goalkeeper:3,Defence:8,Midfield:8,Attack:5};return clamp((targets[position]||5)-(counts[position]||0),-3,4)}
function buyerScore(save,world,buyer,player){const ai=save.aiClubs?.[buyer.id]||{},need=squadNeed(world,buyer,group(player)),qualityGap=(buyer.teamOverall||72)-(player.overall||70),age=player.age||25;let score=45+(ai.transferActivity||50)*.55+(ai.ambition||50)*.35+need*18-Math.max(0,qualityGap-7)*5;if((ai.youthBias||50)>65&&age<=22)score+=18;if((ai.experienceBias||50)>65&&age>=28)score+=10;if(Math.abs(qualityGap)<=5)score+=10;return score}
function chooseBuyer(save,world,player){const candidates=world.clubs.filter(c=>String(c.id)!==String(save.clubId)&&(c.teamOverall||70)>=(player.overall||65)-13);if(!candidates.length)return null;return candidates.map(c=>({club:c,score:buyerScore(save,world,c,player)})).sort((a,b)=>b.score-a.score).slice(0,16)[Math.floor(Math.random()*Math.min(6,candidates.length))]?.club||candidates[0]}
function interestReason(world,buyer,player){const need=squadNeed(world,buyer,group(player));if(need>=2)return`O ${buyer.name} identificou carência em ${group(player)==='Attack'?'ataque':group(player)==='Midfield'?'meio-campo':group(player)==='Defence'?'defesa':'gol'}.`;if((player.age||30)<=21)return`O ${buyer.name} vê potencial de desenvolvimento no jogador.`;if((player.overall||0)>=(buyer.teamOverall||72)+2)return`O ${buyer.name} vê o jogador como reforço de impacto imediato.`;return`O ${buyer.name} considera o jogador compatível com o nível atual do elenco.`}
export function generateIncomingOffer(save,world,currentClub,date){ensurePlan2(save);ensureWorldSimulation(save,world);if(!world?.players?.length||!world?.clubs?.length)return null;const p=chooseOwnPlayer(save,world);if(!p)return null;const buyer=chooseBuyer(save,world,p);if(!buyer)return null;const ai=save.aiClubs?.[buyer.id]||{},preferLoan=(save.loanListed||[]).includes(String(p.id)),preferSale=(save.transferListed||[]).includes(String(p.id)),loanBias=(ai.loanPreference||50)/100,type=preferLoan?'LOAN':preferSale?'BUY':(Math.random()<(.72-loanBias*.3)?'BUY':'LOAN'),value=Math.max(300000,p.marketValue||1000000),style=ai.negotiationStyle||'BALANCED';let offer={id:id('offer'),date,expires:addDays(date,12),status:'PENDING',type,playerId:String(p.id),playerName:p.name,buyerId:String(buyer.id),buyerName:buyer.name,buyerOverall:buyer.teamOverall||72,buyerStyle:style,reason:interestReason(world,buyer,p)};const styleFactor=style==='SPENDER'?1.08:style==='BARGAIN'?.92:style==='AGGRESSIVE'?1.04:1;if(type==='BUY'){offer.amount=Math.round(value*(.84+Math.random()*.27)*styleFactor/10000)*10000;offer.addOns=Math.random()<(style==='BARGAIN'?.62:.43)?Math.round(value*(.03+Math.random()*.09)/10000)*10000:0;offer.sellOnPercent=Math.random()<.34?5+Math.floor(Math.random()*4)*5:0}else{offer.months=Math.random()<.55?12:6;offer.loanFee=Math.round(value*(.01+Math.random()*.045)*styleFactor/10000)*10000;offer.wageShare=50+Math.floor(Math.random()*6)*10;const r=Math.random();offer.optionKind=r<.4?'NONE':r<.79?'OPTION':'OBLIGATION';offer.optionValue=offer.optionKind==='NONE'?0:Math.round(value*(.86+Math.random()*.2)*styleFactor/10000)*10000}save.transferInbox.unshift(offer);save.transferInbox=save.transferInbox.slice(0,40);save.news?.unshift({date,title:`Proposta por ${p.name}`,body:`${buyer.name} enviou uma proposta de ${type==='BUY'?'compra':'empréstimo'}. ${offer.reason}`});return offer}
export function tickPlan2(save,world,currentClub,date){ensurePlan2(save);const reports=processScouting(save,world,date),demands=processPlayerDynamics(save,world,date);save.transferInbox.forEach(o=>{if(o.status==='PENDING'&&o.expires<date)o.status='EXPIRED'});let offer=null,worldEvents=[];const last=save.plan2LastOfferCheck||save.databaseSnapshot||date;if(daysBetween(last,date)>=5){save.plan2LastOfferCheck=date;if(Math.random()<.55||save.transferListed.length||save.loanListed.length)offer=generateIncomingOffer(save,world,currentClub,date)}if(world?.clubs?.length&&save.plan2LastWorldTick!==date){save.plan2LastWorldTick=date;worldEvents=simulateWorldTick(save,world,date,save.clubId)||[]}return{changed:!!offer||reports.length>0||demands.length>0||worldEvents.length>0,offer,reports,demands,worldEvents}}
export function toggleList(save,playerId,type){ensurePlan2(save);const key=type==='LOAN'?'loanListed':'transferListed',other=type==='LOAN'?'transferListed':'loanListed',id=String(playerId);save[other]=save[other].filter(x=>String(x)!==id);save[key]=save[key].some(x=>String(x)===id)?save[key].filter(x=>String(x)!==id):[...save[key],id];return save[key].some(x=>String(x)===id)}
