const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function addDays(date,days){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function stat(save,p){save.playerCareer??={};return save.playerCareer[p.id]??={apps:0,starts:0,minutes:0,goals:0,assists:0,yellow:0,red:0,cleanSheets:0,injuries:0,injuryUntil:null,suspension:0,morale:70,form:p.form??70,energy:p.energy??100,seasonHistory:[],careerGoals:0,careerAssists:0}}
function group(p){const s=`${p.position} ${p.subPosition}`.toLowerCase();if(/goal|keeper/.test(s))return'GK';if(/defen|back/.test(s))return'DEF';if(/mid|winger/.test(s))return'MID';return'ATT'}
function weightedPick(players,weight){if(!players.length)return null;const weights=players.map(p=>Math.max(.05,weight(p))),total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total;for(let i=0;i<players.length;i++){r-=weights[i];if(r<=0)return players[i]}return players[players.length-1]}
export function availableForFixture(players,save,date){return players.filter(p=>{const s=stat(save,p);return(!s.injuryUntil||s.injuryUntil<=date)&&s.suspension<=0})}
export function annotatePlayers(players,save){players.forEach(p=>{const s=stat(save,p);p.morale=s.morale;p.form=s.form;p.energy=s.energy;p.injuryUntil=s.injuryUntil;p.suspension=s.suspension;p.stats=s});return players}
function registeredGoalEvent(result,index,starters){const e=result.playerGoalEvents?.[index];if(!e)return null;const scorer=starters.find(p=>String(p.id)===String(e.scorerId))||starters.find(p=>p.name===e.scorer),assist=e.assistId?starters.find(p=>String(p.id)===String(e.assistId)):starters.find(p=>p.name===e.assist);return scorer?{scorer,assist:assist&&String(assist.id)!==String(scorer.id)?assist:null}:null}
export function processPlayerMatch(save,result,fixture,squad){const starters=result.plan.starters,bench=result.plan.bench,used=[...starters],stats={goals:[],assists:[],cards:[],injuries:[],subs:[]};
 starters.forEach(p=>{const s=stat(save,p);s.apps++;s.starts++;s.minutes+=90;s.form=clamp(s.form+(result.gf>result.ga?2:result.gf<result.ga?-1:.3)+(Math.random()-.5)*2,35,96);s.morale=clamp(s.morale+(result.gf>result.ga?1.2:result.gf<result.ga?-1:.2),20,100);if(group(p)==='GK'&&result.ga===0)s.cleanSheets++});
 const scorerWeight=p=>group(p)==='ATT'?5:group(p)==='MID'?2.4:group(p)==='DEF'?.65:.12;
 for(let i=0;i<result.gf;i++){const registered=registeredGoalEvent(result,i,starters),p=registered?.scorer||weightedPick(starters,scorerWeight);if(!p)continue;const s=stat(save,p);s.goals++;s.careerGoals++;stats.goals.push(p.name);let a=registered?.assist||null;if(!a&&Math.random()<.72){const candidates=starters.filter(x=>x.id!==p.id);a=weightedPick(candidates,x=>group(x)==='MID'?4:group(x)==='ATT'?2.5:1)}if(a){const as=stat(save,a);as.assists++;as.careerAssists++;stats.assists.push(a.name)}}
 const yellowCount=Math.random()<.7?Math.floor(Math.random()*3):0;for(let i=0;i<yellowCount;i++){const p=weightedPick(starters,x=>group(x)==='DEF'?2.8:group(x)==='MID'?1.7:1);if(!p)continue;const s=stat(save,p);s.yellow++;stats.cards.push(`${p.name} (amarelo)`);if(s.yellow>0&&s.yellow%5===0)s.suspension=Math.max(s.suspension,1)}
 if(Math.random()<.055&&starters.length){const p=starters[Math.floor(Math.random()*starters.length)],days=5+Math.floor(Math.random()*40),s=stat(save,p);s.injuries++;s.injuryUntil=addDays(fixture.date,days);stats.injuries.push({name:p.name,days,until:s.injuryUntil});save.news.unshift({date:fixture.date,title:`Lesão: ${p.name}`,body:`O departamento médico estima retorno em cerca de ${days} dias.`})}
 if(Math.random()<.18&&bench.length){const p=bench[Math.floor(Math.random()*bench.length)],s=stat(save,p);s.apps++;s.minutes+=20;s.form=clamp(s.form+(Math.random()-.45)*2,35,96);stats.subs.push(p.name);used.push(p)}
 for(const p of squad){const s=stat(save,p);if(!used.some(x=>String(x.id)===String(p.id)))s.morale=clamp(s.morale-(p.overall>=80?.35:.12),20,100);s.energy=p.energy??s.energy}
 for(const p of squad){const s=stat(save,p);if(s.suspension>0&&!starters.some(x=>String(x.id)===String(p.id)))s.suspension=Math.max(0,s.suspension-1)}
 return stats}
export function recoverAndDevelop(save,players,date,trainingLevel=5,coachYouth=60){for(const p of players){const s=stat(save,p);if(s.injuryUntil&&s.injuryUntil<=date){s.injuryUntil=null;save.news.unshift({date,title:`${p.name} volta a treinar`,body:'O jogador foi liberado pelo departamento médico.'})}const age=p.age??25,growthAge=age<=19?1:age<=22?.65:age<=25?.25:age>=32?-.35:0,potentialGap=Math.max(0,(p.potential||p.overall)-(p.overall||0)),training=(trainingLevel-5)*.025,youth=(coachYouth-60)*.002,chance=.025+Math.max(0,growthAge)*.025+training+Math.max(0,youth);if(potentialGap>0&&Math.random()<chance)p.overall=clamp((p.overall||60)+1,45,p.potential||94);else if(growthAge<0&&Math.random()<Math.abs(growthAge)*.025)p.overall=Math.max(45,(p.overall||60)-1);s.morale=clamp(s.morale+(Math.random()-.5)*.8,20,100);s.form=clamp(s.form+(Math.random()-.5)*.7,35,96)}}
export function closePlayerSeason(save,players,season){for(const p of players){const s=stat(save,p);s.seasonHistory.push({season,apps:s.apps,starts:s.starts,minutes:s.minutes,goals:s.goals,assists:s.assists,yellow:s.yellow,red:s.red,cleanSheets:s.cleanSheets});s.apps=0;s.starts=0;s.minutes=0;s.goals=0;s.assists=0;s.yellow=0;s.red=0;s.cleanSheets=0}}
export function leaders(save,players){const rows=players.map(p=>({player:p,stats:stat(save,p)}));return{goals:[...rows].sort((a,b)=>b.stats.goals-a.stats.goals).slice(0,10),assists:[...rows].sort((a,b)=>b.stats.assists-a.stats.assists).slice(0,10),minutes:[...rows].sort((a,b)=>b.stats.minutes-a.stats.minutes).slice(0,10)}}
