import {state,esc,clubBudgetBase,formatCurrency,SNAPSHOT} from './state.js';
import {currencyOptions,languageOptions,getPreferences,t} from './preferences.js';
import {clubCrestUrl} from './club-assets.js';
const COUNTRY_LABELS={Brazil:'Brasil',England:'Inglaterra',Spain:'Espanha',Italy:'Itália',France:'França','United States':'Estados Unidos','Saudi Arabia':'Arábia Saudita',Germany:'Alemanha',Argentina:'Argentina',Portugal:'Portugal',Netherlands:'Holanda',Belgium:'Bélgica',Turkey:'Turquia'};
const featured=['Brazil','England','Spain','Italy','France','Germany','United States','Saudi Arabia','Argentina','Portugal'];
function displayCountry(x){return COUNTRY_LABELS[x]||x}
function countries(){return [...new Set((state.world?.clubs||[]).map(c=>c.country).filter(Boolean))].sort((a,b)=>{const ia=featured.indexOf(a),ib=featured.indexOf(b);if(ia>=0||ib>=0)return(ia<0?99:ia)-(ib<0?99:ib);return a.localeCompare(b)})}
function leagues(country){return [...new Map((state.world?.clubs||[]).filter(c=>c.country===country).map(c=>[`${c.competitionId}|${c.league}`,{id:c.competitionId,name:c.league}])).values()].sort((a,b)=>a.name.localeCompare(b.name))}
function clubs(country,league){return (state.world?.clubs||[]).filter(c=>c.country===country&&c.league===league).sort((a,b)=>(b.teamOverall||0)-(a.teamOverall||0)||a.name.localeCompare(b.name)).slice(0,80)}
function crest(c,size='normal'){const src=clubCrestUrl(c),initials=esc(c.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase());return `<div class="gcp-pick-crest ${size}">${src?`<img src="${esc(src)}" alt="Escudo ${esc(c.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()">`:''}<span>${initials}</span></div>`}
export function setup(){
 const cs=countries();if(!state.setupFilters.country||!cs.includes(state.setupFilters.country))state.setupFilters.country=cs.includes('Brazil')?'Brazil':cs[0]||'';
 const ls=leagues(state.setupFilters.country);if(!state.setupFilters.league||!ls.some(x=>x.name===state.setupFilters.league))state.setupFilters.league=ls[0]?.name||'';
 const list=clubs(state.setupFilters.country,state.setupFilters.league);if(!list.some(c=>String(c.id)===String(state.selectedClubId)))state.selectedClubId=list[0]?.id||state.selectedClubId;
 const chosen=state.world?.findClub?.(state.selectedClubId)||list[0],p=getPreferences();
 return `<section class="gcp-setup-simple">
 <header class="gcp-pick-head"><button class="gcp-pick-back" id="backCover" aria-label="Voltar">←</button><div class="gcp-pick-brand"><b>GOLAÇO <i>CLASH</i></b><span>Database ${SNAPSHOT.split('-').reverse().join('/')}</span></div><div class="gcp-pick-title"><span>NOVA CARREIRA</span><h1>${t('chooseClub')}</h1></div><div class="gcp-pick-prefs"><select data-pref="language" aria-label="${t('language')}">${languageOptions().map(x=>`<option value="${x.code}" ${x.code===p.language?'selected':''}>${x.label}</option>`).join('')}</select><select data-pref="currency" aria-label="${t('currency')}">${currencyOptions().map(x=>`<option value="${x.code}" ${x.code===p.currency?'selected':''}>${x.label}</option>`).join('')}</select></div></header>
 <div class="gcp-pick-filters"><label><span>${t('country')}</span><select id="setupCountrySelect">${cs.map(c=>`<option value="${esc(c)}" ${c===state.setupFilters.country?'selected':''}>${esc(displayCountry(c))}</option>`).join('')}</select></label><label><span>${t('league')}</span><select id="setupLeagueSelect">${ls.map(l=>`<option value="${esc(l.name)}" ${l.name===state.setupFilters.league?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><div class="gcp-pick-hint"><b>Escolha o time</b><span>Toque em um clube e confirme abaixo.</span></div></div>
 <div class="gcp-pick-body"><div class="gcp-pick-clubs" role="list">${list.map(c=>`<button role="listitem" data-club-id="${c.id}" class="gcp-pick-club ${String(c.id)===String(state.selectedClubId)?'active':''}">${crest(c)}<span><b>${esc(c.name)}</b><small>${esc(c.coachName||'Técnico atual')}</small></span><strong>${c.teamOverall||72}</strong></button>`).join('')||'<div class="gcp-pick-empty">Nenhum clube disponível nesta liga.</div>'}</div>${chosen?selected(chosen):''}</div>
 <div class="gcp-president-compact"><label><span>Presidente</span><input id="presidentName" value="Presidente"></label><label><span>Nacionalidade</span><input id="nationality" value="Brasil"></label><label><span>Nascimento</span><input id="presidentBirth" type="date" value="1990-01-01"></label><label><span>Perfil</span><select id="presidentStyle"><option>Personalizado</option><option>Ambicioso</option><option>Negociador</option><option>Formador</option><option>Gastador</option><option>Conservador</option></select></label></div>
 </section>`;
}
function selected(c){return `<aside class="gcp-pick-selected">${crest(c,'big')}<div class="gcp-pick-selected-name"><span>CLUBE SELECIONADO</span><h2>${esc(c.name)}</h2><p>${esc(c.league)} • ${esc(displayCountry(c.country))}</p></div><div class="gcp-pick-facts"><div><span>OVR</span><b>${c.teamOverall||72}</b></div><div><span>Técnico</span><b>${esc(c.coachName||'Interino atual')}</b></div><div><span>Estádio</span><b>${esc(c.stadium||'Não informado')}</b></div><div><span>Orçamento</span><b>${formatCurrency(clubBudgetBase(c))}</b></div></div><button class="gcp-pick-start" id="startCareer">Assumir ${esc(c.name)} <i>›</i></button></aside>`}
