import {state,esc,clubBudgetBase,formatCurrency,SNAPSHOT} from './state.js';
import {leagueProfile} from './game.js';
import {currencyOptions,languageOptions,getPreferences,t} from './preferences.js';

const CODES={Brazil:'br',Brasil:'br',England:'gb-eng',Inglaterra:'gb-eng',Spain:'es',Espanha:'es',Italy:'it',Itália:'it',France:'fr',França:'fr','United States':'us',USA:'us','Saudi Arabia':'sa','Arábia Saudita':'sa',Germany:'de',Alemanha:'de',Argentina:'ar',Portugal:'pt',Netherlands:'nl',Belgium:'be',Turkey:'tr'};
const COUNTRY_LABELS={Brazil:'Brasil',England:'Inglaterra',Spain:'Espanha',Italy:'Itália',France:'França','United States':'Estados Unidos','Saudi Arabia':'Arábia Saudita',Germany:'Alemanha',Argentina:'Argentina',Portugal:'Portugal',Netherlands:'Holanda',Belgium:'Bélgica',Turkey:'Turquia'};
const featured=['Brazil','England','Spain','Italy','France','Germany','United States','Saudi Arabia','Argentina','Portugal'];
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const flagUrl=country=>`https://flagcdn.com/w80/${CODES[country]||'un'}.png`;
const leagueLogo=id=>id?`https://tmssl.akamaized.net/images/logo/normal/${String(id).toLowerCase()}.png`:'https://tmssl.akamaized.net/images/logo/normal/default.png';
const clubCrest=id=>`https://tmssl.akamaized.net/images/wappen/head/${id}.png`;
function displayCountry(x){return COUNTRY_LABELS[x]||x;}
function sortedCountries(){const all=[...new Set(state.world.clubs.map(c=>c.country).filter(Boolean))];return all.sort((a,b)=>{const ia=featured.indexOf(a),ib=featured.indexOf(b);if(ia>=0||ib>=0)return(ia<0?99:ia)-(ib<0?99:ib);return a.localeCompare(b)})}
function leaguesFor(country){const map=new Map();state.world.clubs.filter(c=>c.country===country).forEach(c=>{const key=`${c.competitionId}|${c.league}`;if(!map.has(key))map.set(key,{id:c.competitionId,name:c.league,count:0});map.get(key).count++});return[...map.values()].sort((a,b)=>{const na=norm(a.name),nb=norm(b.name);const rank=x=>/serie a|premier league$|la liga$|serie a$|ligue 1/.test(x)?0:/serie b|championship|segunda|serie b$|ligue 2/.test(x)?1:2;return rank(na)-rank(nb)||a.name.localeCompare(b.name)})}
function clubsFor(country,league){return state.world.clubs.filter(c=>c.country===country&&c.league===league).sort((a,b)=>(b.teamOverall||0)-(a.teamOverall||0)||a.name.localeCompare(b.name)).slice(0,60)}

export function setup(){
 const countries=sortedCountries();
 if(!state.setupFilters.country||!countries.includes(state.setupFilters.country))state.setupFilters.country=countries.includes('Brazil')?'Brazil':countries[0]||'';
 const leagues=leaguesFor(state.setupFilters.country);
 if(!state.setupFilters.league||!leagues.some(l=>l.name===state.setupFilters.league))state.setupFilters.league=leagues[0]?.name||'';
 const clubs=clubsFor(state.setupFilters.country,state.setupFilters.league);
 if(!clubs.some(c=>String(c.id)===String(state.selectedClubId)))state.selectedClubId=clubs[0]?.id||state.selectedClubId;
 const chosen=state.world.findClub(state.selectedClubId)||clubs[0],p=getPreferences();
 return `<section class="cd-setup-v3">
   <header class="cd-setup-header"><button class="cd-back" id="backCover">←</button><img src="./assets/brand/club-dynasty-26-logo.webp?v=20260818-9" alt="Club Dynasty 26"><div><strong>${t('chooseClub')}</strong><span>Database ${SNAPSHOT.split('-').reverse().join('/')}</span></div><div class="cd-setup-quick"><label>${t('currency')}<select data-pref="currency" id="setupCurrency">${currencyOptions().map(x=>`<option value="${x.code}" ${x.code===p.currency?'selected':''}>${x.label}</option>`).join('')}</select></label><label>${t('language')}<select data-pref="language" id="setupLanguage">${languageOptions().map(x=>`<option value="${x.code}" ${x.code===p.language?'selected':''}>${x.label}</option>`).join('')}</select></label></div></header>
   <div class="cd-setup-hero"><img src="./assets/brand/club-dynasty-26-club-select.webp?v=20260818-9" alt="Arte de escolha de clube"><div><span>CLUB DYNASTY 26</span><h1>${t('chooseClub')}</h1><p>País → liga → clube. Escolha a sua rota e comece uma nova dinastia.</p></div></div>
   <div class="cd-president-strip"><div class="field"><label>Nome do presidente</label><input id="presidentName" value="Presidente"></div><div class="field"><label>Nacionalidade</label><input id="nationality" value="Brasil"></div><div class="field"><label>Data de nascimento</label><input id="presidentBirth" type="date" value="1990-01-01"></div><div class="field"><label>Estilo</label><select id="presidentStyle"><option>Personalizado</option><option>Ambicioso</option><option>Negociador</option><option>Formador</option><option>Gastador</option><option>Conservador</option></select></div></div>
   <div class="cd-choice-grid">
    <section class="cd-choice-column countries"><div class="cd-step"><b>1</b><div><span>${t('country')}</span><strong>${t('chooseCountry')}</strong></div></div><div class="cd-country-list">${countries.map(c=>`<button data-country="${esc(c)}" class="cd-country ${c===state.setupFilters.country?'active':''}"><img src="${flagUrl(c)}" alt="Bandeira de ${esc(displayCountry(c))}" onerror="this.style.display='none'"><span>${esc(displayCountry(c))}</span><i>›</i></button>`).join('')}</div></section>
    <section class="cd-choice-column leagues"><div class="cd-step"><b>2</b><div><span>${t('league')}</span><strong>${t('chooseLeague')}</strong></div></div><div class="cd-league-list">${leagues.map(l=>`<button data-league="${esc(l.name)}" class="cd-league ${l.name===state.setupFilters.league?'active':''}"><div class="cd-league-logo"><img src="${leagueLogo(l.id)}" alt="${esc(l.name)}" onerror="this.style.display='none'"><span>${esc((l.name||'LG').split(/\s+/).map(x=>x[0]).slice(0,3).join('').toUpperCase())}</span></div><div><strong>${esc(l.name)}</strong><small>${l.count} clubes</small></div><i>›</i></button>`).join('')||'<div class="cd-empty">Nenhuma liga disponível.</div>'}</div></section>
    <section class="cd-choice-column clubs"><div class="cd-step"><b>3</b><div><span>${t('club')}</span><strong>${t('chooseClub')}</strong></div></div><div class="cd-club-grid">${clubs.map(c=>`<button data-club-id="${c.id}" class="cd-club-card ${String(c.id)===String(state.selectedClubId)?'active':''}"><div class="cd-club-crest"><img src="${clubCrest(c.id)}" alt="Escudo ${esc(c.name)}" onerror="this.style.display='none'"><span>${esc(c.name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span></div><div class="cd-club-copy"><strong>${esc(c.name)}</strong><small>${esc(c.coachName||'Técnico a confirmar')}</small><span>${esc(c.stadium||'Estádio não informado')}</span></div><b class="cd-ovr">${c.teamOverall||72}</b></button>`).join('')}</div></section>
   </div>
   ${chosen?preview(chosen):''}
 </section>`;
}
function preview(c){const p=leagueProfile(c.league);return `<section class="cd-selected-club"><div class="cd-selected-main"><div class="cd-club-crest big"><img src="${clubCrest(c.id)}" alt="${esc(c.name)}" onerror="this.style.display='none'"><span>${esc(c.name.slice(0,2).toUpperCase())}</span></div><div><span class="cd-kicker">CLUBE SELECIONADO</span><h2>${esc(c.name)}</h2><p>${esc(c.league)} • ${esc(displayCountry(c.country))}</p></div><div class="cd-selected-rating"><span>OVR</span><b>${c.teamOverall||72}</b></div></div><div class="cd-selected-facts"><div><span>Técnico</span><b>${esc(c.coachName||'A confirmar')}</b></div><div><span>Estádio</span><b>${esc(c.stadium)}</b></div><div><span>Orçamento-base</span><b>${formatCurrency(clubBudgetBase(c))}</b></div><div><span>Formato</span><b>${esc(p.format)}</b></div></div><div class="cd-story"><span>MINI HISTÓRIA</span><p>${esc(c.history)}</p></div><button class="cd-start-career" id="startCareer">Assumir ${esc(c.name)} <i>›</i></button></section>`}
