import {state,esc,formatDate,contractLabel,squad,nextFixture,teamOverall} from './state.js';
import {coachSelection} from './game-v6.js';
import {loadingPlayers,noPlayers,ratingClass} from './views.js';
import {playerPhoto} from './media.js';
import {formatCompactMoneyEUR} from './preferences.js';
import {ensurePlan2} from './plan2-engine.js';
import {playerDynamicsSummary,squadWageContext,currentPlayerWage} from './player-dynamics.js';
import {FORMATION_NAMES,formationSlots,assignPlayersToFormation,applyPresidentLineup,positionFit,fitLabel,effectiveOverall} from './lineup-state.js';
import {installLineupActions} from './lineup-actions.js';
installLineupActions();

export function squadPage(){
 ensurePlan2(state.save);
 if(state.playersLoading)return `<div class="hero"><div><h1>Plantel</h1></div></div>${loadingPlayers()}`;
 if(!state.playersReady||!state.world.players?.length)return `<div class="hero"><div><h1>Plantel</h1></div></div>${noPlayers()}`;
 const players=squad().sort((a,b)=>(b.overall||0)-(a.overall||0)),fx=nextFixture(),coachPlan=fx&&players.length>=11?coachSelection(players,fx,nextFixture(1),teamOverall(),state.save.coach):players.length>=11?coachSelection(players,{id:'preview',date:state.save.date,opponentOverall:teamOverall(),importance:1,type:'LEAGUE',home:true},null,teamOverall(),state.save.coach):null,manual=!!state.save.presidentLineup?.enabled,manualPlan=manual&&coachPlan?applyPresidentLineup(coachPlan,players,state.save.presidentLineup):null,plan=manualPlan||coachPlan,formation=manual?(state.save.presidentLineup?.formation||plan?.preferredFormation||'4-3-3'):(plan?.preferredFormation||'4-3-3'),assignments=displayAssignments(players,plan,formation,manual),starterIds=new Set(assignments.map(x=>String(x.player?.id||'')).filter(Boolean)),bench=players.filter(p=>!starterIds.has(String(p.id))),selected=players.find(p=>String(p.id)===String(state.selectedSquadPlayerId)),wages=squadWageContext(state.save,players),pending=(state.save.playerDemands||[]).filter(d=>d.status==='PENDING').length;
 return `<div class="cd-squad-v4"><div class="hero cd-plantel-hero"><div><span class="eyebrow">PLANTEL & ESCALAÇÃO</span><h1>${players.length} jogadores</h1><p>${manual?'Você está intervindo na escalação. A próxima partida usa os 11 definidos aqui.':'O técnico controla a escalação. Você pode assumir o controle quando quiser.'}</p></div><div class="cd-lineup-summary ${manual?'president':''}"><span>${manual?'INTERVENÇÃO DA PRESIDÊNCIA':esc(state.save.coach.name)}</span><b>${esc(formation)} • OVR ${plan?.lineupOverall??teamOverall()}</b><small>${manual?'Escalação manual ativa':plan?.rotation>=.4?'Time misto':plan?.rotation>=.15?'Rodízio':'Força máxima'}</small></div></div>${lineupBoard(players,assignments,bench,plan,formation,manual)}<div class="grid grid-3 cd-wage-overview"><div class="card"><span class="eyebrow">MAIOR SALÁRIO</span><b>${formatCompactMoneyEUR(wages.top)}/sem</b><small>Referência da folha</small></div><div class="card"><span class="eyebrow">MEDIANA DA FOLHA</span><b>${formatCompactMoneyEUR(wages.median)}/sem</b><small>Base da hierarquia salarial</small></div><div class="card ${pending?'cd-attention-card':''}"><span class="eyebrow">PEDIDOS DO PLANTEL</span><b>${pending}</b><small>${pending?'Há conversas que precisam da presidência':'Vestiário sem pedidos pendentes'}</small></div></div><h2 class="section-title">Lista do plantel</h2><div class="split-view cd-squad-layout"><div class="table-wrap"><table><thead><tr><th>Status</th><th>Jogador</th><th>Posição</th><th>OVR</th><th>POT</th><th>Felicidade</th><th>Contrato</th><th>Salário</th></tr></thead><tbody>${players.map(p=>row(p,starterIds,players)).join('')}</tbody></table></div>${selected?panel(selected,starterIds.has(String(selected.id)),players):empty()}</div></div>`;
}

function displayAssignments(players,plan,formation,manual){
 const slots=formationSlots(formation),byId=new Map(players.map(p=>[String(p.id),p]));
 if(manual&&state.save.presidentLineup?.slots?.length)return slots.map(([key,slot,x,y])=>({key,slot,x,y,player:byId.get(String(state.save.presidentLineup.slots.find(s=>s.key===key)?.playerId||''))||null}));
 const picked=assignPlayersToFormation(plan?.starters||[],formation,(plan?.starters||[]).map(p=>String(p.id))),map=new Map(picked.map(s=>[s.key,s.playerId]));return slots.map(([key,slot,x,y])=>({key,slot,x,y,player:byId.get(String(map.get(key)||''))||null}));
}
function shortName(name=''){const p=String(name).trim().split(/\s+/);return p.length>1?p.at(-1):p[0]||'—'}
function lineupBoard(players,assignments,bench,plan,formation,manual){return `<section class="card cd-plantel-card"><div class="cd-plantel-toolbar"><div><span class="eyebrow">ESCALAÇÃO ATUAL</span><h2>${manual?'Sua escalação':'Escalação de '+esc(state.save.coach.name)}</h2><p>${manual?'Toque em dois jogadores para trocar. No computador, você também pode arrastar.':'Ative a intervenção para mudar jogadores ou formação.'}</p></div><div class="cd-plantel-tools"><label><span>Formação</span><select id="lineupFormation">${FORMATION_NAMES.map(f=>`<option value="${f}" ${f===formation?'selected':''}>${f}</option>`).join('')}</select></label>${manual?`<button class="button secondary" data-lineup-reset>Usar sugestão do técnico</button><button class="button ghost" data-lineup-auto>Devolver ao técnico</button>`:`<button class="button" data-lineup-edit>Editar escalação</button>`}</div></div><div class="cd-plantel-main"><div class="cd-tactical-pitch"><div class="cd-pitch-markings"><i class="half"></i><i class="circle"></i><i class="box top"></i><i class="box bottom"></i></div>${assignments.map(a=>pitchPlayer(a,manual)).join('')}</div><aside class="cd-plantel-bench"><div class="cd-bench-head"><div><span class="eyebrow">BANCO & RESERVAS</span><b>${bench.length} jogadores</b></div><small>${manual?'Toque em um reserva e depois na posição desejada.':'Fotos e OVR do restante do elenco.'}</small></div><div class="cd-bench-grid">${bench.map(p=>benchPlayer(p,manual)).join('')}</div></aside></div><footer class="cd-plantel-footer"><div><span>OVR da escalação</span><b>${plan?.lineupOverall??'—'}</b></div><div><span>Formação</span><b>${esc(formation)}</b></div><div><span>Controle</span><b>${manual?'Presidência':'Técnico'}</b></div>${manual&&plan?.fitAverage!=null?`<div><span>Encaixe posicional</span><b>${Math.round(plan.fitAverage*100)}%</b></div>`:''}</footer></section>`}
function pitchPlayer(a,manual){const p=a.player;if(!p)return `<button class="cd-pitch-player empty" style="left:${a.x}%;top:${a.y}%" data-lineup-slot="${a.key}"><span class="cd-position-chip">${a.slot}</span><b>+</b><small>Vaga</small></button>`;const fit=positionFit(p,a.slot),effective=effectiveOverall(p,a.slot),out=fit<.9;return `<button class="cd-pitch-player ${manual?'editable':''} ${out?'out-position':''}" style="left:${a.x}%;top:${a.y}%" data-lineup-slot="${a.key}" data-lineup-player="${p.id}" data-player-id="${p.id}" draggable="${manual?'true':'false'}"><span class="cd-position-chip">${a.slot}</span><span class="cd-pitch-ovr ${ratingClass(p.overall)}">${p.overall}</span>${playerPhoto(p,{size:'md',className:'cd-pitch-photo'})}<b>${esc(shortName(p.name))}</b><small>${out?`${fitLabel(fit)} • efetivo ${effective}`:esc(p.subPosition||p.position||'')}</small></button>`}
function benchPlayer(p,manual){return `<button class="cd-bench-player ${manual?'editable':''}" data-lineup-bench="${p.id}" data-lineup-player="${p.id}" draggable="${manual?'true':'false'}">${playerPhoto(p,{size:'sm'})}<span><b>${esc(shortName(p.name))}</b><small>${esc(p.subPosition||p.position||'')}</small></span><em class="rating ${ratingClass(p.overall)}">${p.overall}</em></button>`}
function row(p,xi,players){const sale=(state.save.transferListed||[]).includes(String(p.id)),loan=(state.save.loanListed||[]).includes(String(p.id)),dyn=playerDynamicsSummary(state.save,p,players);return `<tr class="clickable ${String(p.id)===String(state.selectedSquadPlayerId)?'selected':''}" data-p2-squad-player="${p.id}"><td>${xi.has(String(p.id))?'<span class="pill ok">XI</span>':'<span class="pill">Banco</span>'}${sale?'<small class="cd-list-tag sale">À venda</small>':''}${loan?'<small class="cd-list-tag loan">Empréstimo</small>':''}${dyn.pending?'<small class="cd-list-tag demand">Pedido</small>':''}</td><td><div class="fp-player-cell">${playerPhoto(p,{size:'sm'})}<div><b>${esc(p.name)}</b><small>${esc(p.nationality||'')}</small></div></div></td><td>${esc(p.subPosition||p.position)}</td><td><b class="rating ${ratingClass(p.overall)}">${p.overall}</b></td><td>${p.potential}</td><td><span class="cd-happiness ${dyn.happiness<45?'low':dyn.happiness>=75?'high':''}">${Math.round(dyn.happiness)}/100</span></td><td>${contractLabel(p.contractExpiration)}<small>${p.contractExpiration?formatDate(p.contractExpiration):''}</small></td><td>${formatCompactMoneyEUR(currentPlayerWage(state.save,p))}/sem</td></tr>`}
function demandCard(d){if(!d)return'';const title={RENEWAL:'Quer renovar',WAGE:'Quer rever o salário',ROLE:'Quer mais espaço',TRANSFER:'Pediu para sair'}[d.type]||'Conversa pendente';const actions=d.type==='ROLE'?`<button class="button compact" data-player-demand="PROMISE">Prometer oportunidades</button><button class="button ghost compact" data-player-demand="REFUSE">Não prometer</button>`:d.type==='TRANSFER'?`<button class="button secondary compact" data-player-demand="LIST">Ouvir propostas</button><button class="button ghost compact" data-player-demand="REFUSE">Recusar pedido</button>`:`<button class="button compact" data-player-demand="ACKNOWLEDGE">Abrir renovação</button><button class="button ghost compact" data-player-demand="REFUSE">Adiar</button>`;return `<div class="cd-player-demand ${d.priority==='HIGH'?'urgent':''}"><span class="eyebrow">CONVERSA DO JOGADOR</span><h3>${title}</h3><p>${esc(d.message)}</p><small>Responder até ${formatDate(d.expires)}</small><div>${actions}</div></div>`}
function panel(p,isXI,players){const sale=(state.save.transferListed||[]).includes(String(p.id)),loan=(state.save.loanListed||[]).includes(String(p.id)),offers=(state.save.transferInbox||[]).filter(o=>o.status==='PENDING'&&String(o.playerId)===String(p.id)),dyn=playerDynamicsSummary(state.save,p,players),contract=state.save.playerContracts?.[p.id]||{},roleLabel={KEY:'Jogador-chave',STARTER:'Titular',ROTATION:'Rotação',PROSPECT:'Projeto'}[dyn.role]||dyn.role;return `<aside class="detail-panel card cd-player-management"><div class="player-head">${playerPhoto(p,{size:'lg'})}<div><span class="eyebrow">${isXI?'TITULAR NA ESCALAÇÃO':'PLANTEL'}</span><h2>${esc(p.name)}</h2><p>${esc(p.subPosition||p.position)} • ${p.age??'—'} anos</p></div><b class="rating huge ${ratingClass(p.overall)}">${p.overall}</b></div><div class="cd-player-mind"><div><span>Felicidade</span><b>${Math.round(dyn.happiness)}/100</b></div><div><span>Perfil de gameplay</span><b>${esc(dyn.personality.archetype)}</b></div><div><span>Papel prometido</span><b>${esc(roleLabel)}</b></div><div><span>Titular recente</span><b>${Math.round(dyn.startRate*100)}%</b></div></div>${demandCard(dyn.pending)}<div class="fact-list compact"><div><span>Contrato</span><b>${contractLabel(p.contractExpiration)}</b></div><div><span>Fim</span><b>${formatDate(p.contractExpiration)}</b></div><div><span>Valor</span><b>${p.marketValue?formatCompactMoneyEUR(p.marketValue):'—'}</b></div><div><span>Salário atual</span><b>${formatCompactMoneyEUR(dyn.wage)}/sem</b></div><div><span>Cláusula</span><b>${contract.releaseClause?formatCompactMoneyEUR(contract.releaseClause):'Sem cláusula'}</b></div><div><span>Forma / energia</span><b>${Math.round(p.form??70)} / ${Math.round(p.energy??100)}%</b></div></div>${offers.length?`<button class="cd-player-offers" data-page="inbox"><span>${offers.length} proposta(s) por este jogador</span><b>Abrir central ›</b></button>`:''}<div class="cd-player-actions"><button class="button full" id="p2RenewPlayer">Renovar contrato</button><button class="button secondary full" id="p2ToggleSale">${sale?'Retirar da lista de venda':'Colocar à venda'}</button><button class="button secondary full" id="p2ToggleLoan">${loan?'Retirar da lista de empréstimo':'Disponibilizar por empréstimo'}</button></div></aside>`}
function empty(){return `<aside class="detail-panel card cd-empty-state"><h2>Selecione um jogador</h2><p>Além do plantel tático, aqui você gerencia contrato, mercado, felicidade e papel no elenco.</p></aside>`}
