import {state,esc,formatDate,contractLabel,squad,nextFixture,teamOverall} from './state.js';
import {coachSelection} from './game-v3.js';
import {loadingPlayers,noPlayers,ratingClass} from './views.js';
import {playerPhoto} from './media.js';
import {formatCompactMoneyEUR} from './preferences.js';
import {ensurePlan2} from './plan2-engine.js';
export function squadPage(){ensurePlan2(state.save);if(state.playersLoading)return `<div class="hero"><div><h1>Elenco</h1></div></div>${loadingPlayers()}`;if(!state.playersReady||!state.world.players?.length)return `<div class="hero"><div><h1>Elenco</h1></div></div>${noPlayers()}`;const players=squad().sort((a,b)=>(b.overall||0)-(a.overall||0)),fx=nextFixture(),plan=fx&&players.length>=11?coachSelection(players,fx,nextFixture(1),teamOverall(),state.save.coach):null,xi=new Set(plan?.starters.map(p=>String(p.id))||[]),selected=players.find(p=>String(p.id)===String(state.selectedSquadPlayerId));return `<div class="hero"><div><span class="eyebrow">ELENCO PROFISSIONAL</span><h1>${players.length} jogadores</h1><p>Contratos e mercado são da presidência. Escalação e funções são do técnico.</p></div>${plan?`<div class="cd-lineup-summary"><span>${esc(state.save.coach.name)}</span><b>${esc(plan.preferredFormation)} • OVR ${plan.lineupOverall}</b><small>${plan.rotation>=.4?'Time misto':plan.rotation>=.15?'Rodízio':'Força máxima'}</small></div>`:''}</div><div class="split-view cd-squad-layout"><div class="table-wrap"><table><thead><tr><th>Status</th><th>Jogador</th><th>Posição</th><th>OVR</th><th>POT</th><th>Energia</th><th>Contrato</th><th>Valor</th></tr></thead><tbody>${players.map(p=>row(p,xi)).join('')}</tbody></table></div>${selected?panel(selected,xi.has(String(selected.id))):empty()}</div>`}
function row(p,xi){const sale=(state.save.transferListed||[]).includes(String(p.id)),loan=(state.save.loanListed||[]).includes(String(p.id));return `<tr class="clickable ${String(p.id)===String(state.selectedSquadPlayerId)?'selected':''}" data-p2-squad-player="${p.id}"><td>${xi.has(String(p.id))?'<span class="pill ok">XI</span>':'<span class="pill">Banco</span>'}${sale?'<small class="cd-list-tag sale">À venda</small>':''}${loan?'<small class="cd-list-tag loan">Empréstimo</small>':''}</td><td><div class="fp-player-cell">${playerPhoto(p,{size:'sm'})}<div><b>${esc(p.name)}</b><small>${esc(p.nationality||'')}</small></div></div></td><td>${esc(p.subPosition||p.position)}</td><td><b class="rating ${ratingClass(p.overall)}">${p.overall}</b></td><td>${p.potential}</td><td>${Math.round(p.energy??100)}%</td><td>${contractLabel(p.contractExpiration)}<small>${p.contractExpiration?formatDate(p.contractExpiration):''}</small></td><td>${p.marketValue?formatCompactMoneyEUR(p.marketValue):'—'}</td></tr>`}
function panel(p,isXI){const sale=(state.save.transferListed||[]).includes(String(p.id)),loan=(state.save.loanListed||[]).includes(String(p.id)),offers=(state.save.transferInbox||[]).filter(o=>o.status==='PENDING'&&String(o.playerId)===String(p.id));return `<aside class="detail-panel card cd-player-management"><div class="player-head">${playerPhoto(p,{size:'lg'})}<div><span class="eyebrow">${isXI?'PROVÁVEL TITULAR':'ELENCO'}</span><h2>${esc(p.name)}</h2><p>${esc(p.subPosition||p.position)} • ${p.age??'—'} anos</p></div><b class="rating huge ${ratingClass(p.overall)}">${p.overall}</b></div><div class="fact-list compact"><div><span>Contrato</span><b>${contractLabel(p.contractExpiration)}</b></div><div><span>Fim</span><b>${formatDate(p.contractExpiration)}</b></div><div><span>Valor</span><b>${p.marketValue?formatCompactMoneyEUR(p.marketValue):'—'}</b></div><div><span>Salário estimado</span><b>${formatCompactMoneyEUR(p.estimatedWage||0)}</b></div><div><span>Energia</span><b>${Math.round(p.energy??100)}%</b></div><div><span>Forma</span><b>${Math.round(p.form??70)}/100</b></div></div>${offers.length?`<button class="cd-player-offers" data-page="inbox"><span>${offers.length} proposta(s) por este jogador</span><b>Abrir central ›</b></button>`:''}<div class="cd-player-actions"><button class="button full" id="p2RenewPlayer">Renovar contrato</button><button class="button secondary full" id="p2ToggleSale">${sale?'Retirar da lista de venda':'Colocar à venda'}</button><button class="button secondary full" id="p2ToggleLoan">${loan?'Retirar da lista de empréstimo':'Disponibilizar por empréstimo'}</button></div><small class="subtle">Colocar um jogador no mercado aumenta a chance de outros clubes enviarem propostas.</small></aside>`}
function empty(){return `<aside class="detail-panel card cd-empty-state"><h2>Selecione um jogador</h2><p>Gerencie contrato, venda e empréstimo sem interferir na escalação do técnico.</p></aside>`}
