const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const month=date=>Number(String(date).slice(5,7));
const addYears=(date,years)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString().slice(0,10)};
export function transferWindow(country='',date='2026-08-14'){
 const c=country.toLowerCase(),m=month(date);
 if(c.includes('brazil')||c.includes('brasil'))return{open:[1,2,3,7,8,9].includes(m),label:'Janelas brasileiras do calendário anual'};
 if(c.includes('usa')||c.includes('united states'))return{open:[1,2,3,4,7,8].includes(m),label:'Janelas MLS/USL'};
 if(c.includes('saudi')||c.includes('arab'))return{open:[1,2,7,8,9].includes(m),label:'Janelas sauditas'};
 return{open:[1,8].includes(m),label:'Janela principal europeia'};
}
export function structuredOffer({upfront=0,installments=0,installmentCount=0,appearanceBonus=0,titleBonus=0,sellOn=0,playerExchangeValue=0}){const future=Number(installments)||0,bonuses=(Number(appearanceBonus)||0)+(Number(titleBonus)||0),total=(Number(upfront)||0)+future+bonuses+(Number(playerExchangeValue)||0);return{upfront:Number(upfront)||0,installments:future,installmentCount:Math.max(0,Number(installmentCount)||0),appearanceBonus:Number(appearanceBonus)||0,titleBonus:Number(titleBonus)||0,sellOn:clamp(Number(sellOn)||0,0,50),playerExchangeValue:Number(playerExchangeValue)||0,total,presentValue:(Number(upfront)||0)+future*.92+bonuses*.35+(Number(playerExchangeValue)||0)}}
export function evaluateStructuredOffer(player,offer,ask){const ratio=offer.presentValue/Math.max(1,ask);let chance=.1;if(ratio>=1.05)chance=.96;else if(ratio>=.98)chance=.78;else if(ratio>=.9)chance=.48;else if(ratio>=.82)chance=.2;if(offer.sellOn>=10)chance+=.06;if(offer.upfront/Math.max(1,offer.total)<.35)chance-=.08;return{accepted:Math.random()<clamp(chance,.03,.98),ratio,expectedCounter:Math.round(ask*(1.01+Math.random()*.09)/10000)*10000}}
export function createPaymentSchedule(offer,date){const payments=[];if(offer.upfront)payments.push({date,amount:offer.upfront,type:'UPFRONT'});if(offer.installments&&offer.installmentCount){const each=Math.round(offer.installments/offer.installmentCount);for(let i=1;i<=offer.installmentCount;i++){const d=new Date(`${date}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+i*6);payments.push({date:d.toISOString().slice(0,10),amount:i===offer.installmentCount?offer.installments-each*(i-1):each,type:'INSTALLMENT'})}}return payments}
export function processDuePayments(save,date){save.transferPayments??=[];const due=save.transferPayments.filter(p=>!p.paid&&p.date<=date);for(const p of due){save.cash-=p.amount;p.paid=true;save.transactions.push({date,type:'Parcela de transferência',description:p.description||'Parcela contratual',amount:-p.amount});save.news?.unshift({date,title:'Parcela de transferência paga',body:`Pagamento contratual de ${p.description||'uma transferência'} debitado do caixa.`})}return due}
export function loanProposal(player,{months=12,loanFee=0,wageShare=100,buyOption=0,buyObligation=0}={}){return{playerId:player.id,months:clamp(Number(months)||12,1,24),loanFee:Math.max(0,Number(loanFee)||0),wageShare:clamp(Number(wageShare)||100,0,100),buyOption:Math.max(0,Number(buyOption)||0),buyObligation:Math.max(0,Number(buyObligation)||0)}}
export function evaluateLoan(player,proposal,buyer,seller){const opportunity=(buyer?.teamOverall||70)-(seller?.teamOverall||70),minutesNeed=player.overall<(seller?.teamOverall||72)+4;let chance=.35+(proposal.wageShare/100)*.25+(proposal.loanFee/Math.max(1,player.marketValue))*.35+(minutesNeed ? .15 : 0)+(opportunity>-6 ? .08 : 0);if(proposal.buyObligation)chance+=.12;return Math.random()<clamp(chance,.08,.92)}
export function registerLoan(save,player,proposal,date){save.loans??=[];const end=new Date(`${date}T12:00:00Z`);end.setUTCMonth(end.getUTCMonth()+proposal.months);const optionKind=proposal.optionKind||(proposal.buyObligation?'OBLIGATION':proposal.buyOption?'OPTION':'NONE'),optionValue=proposal.optionValue||proposal.buyObligation||proposal.buyOption||0;save.loans.push({...proposal,optionKind,optionValue,playerId:String(player.id),playerName:player.name,parentClubId:String(player.currentClubId||''),parentClubName:player.currentClubName||'',start:date,end:end.toISOString().slice(0,10),active:true,direction:'IN'});save.cash-=proposal.loanFee;save.transactions.push({date,type:'Empréstimo',description:`Taxa de empréstimo por ${player.name}`,amount:-proposal.loanFee})}
function buyLoanedIn(save,l,date,price){if(price<=0||save.cash<price||save.transferBudget<price)return false;save.cash-=price;save.transferBudget-=price;save.acquiredPlayerIds??=[];if(!save.acquiredPlayerIds.some(id=>String(id)===String(l.playerId)))save.acquiredPlayerIds.push(String(l.playerId));save.playerContracts??={};save.playerContracts[l.playerId]={...(save.playerContracts[l.playerId]||{}),until:addYears(date,4),salary:save.playerContracts[l.playerId]?.salary||0};save.transactions?.push({date,type:'Compra após empréstimo',description:l.playerName,amount:-price});save.presidentStats&&(save.presidentStats.bought=(save.presidentStats.bought||0)+1,save.presidentStats.moneySpent=(save.presidentStats.moneySpent||0)+price);if(save.records)save.records.biggestBuy=Math.max(save.records.biggestBuy||0,price);save.news?.unshift({date,title:`${l.playerName} comprado em definitivo`,body:`A cláusula de compra do empréstimo foi executada.`});l.purchaseExecuted=true;l.purchasePrice=price;return true}
function sellLoanedOut(save,l,date,price){if(price<=0)return false;save.soldPlayerIds??=[];save.acquiredPlayerIds??=[];if(!save.soldPlayerIds.some(id=>String(id)===String(l.playerId)))save.soldPlayerIds.push(String(l.playerId));save.acquiredPlayerIds=save.acquiredPlayerIds.filter(id=>String(id)!==String(l.playerId));save.cash+=price;save.transferBudget+=price;save.transactions?.push({date,type:'Venda após empréstimo',description:l.playerName,amount:price});if(save.presidentStats){save.presidentStats.sold=(save.presidentStats.sold||0)+1;save.presidentStats.moneyReceived=(save.presidentStats.moneyReceived||0)+price}if(save.records)save.records.biggestSale=Math.max(save.records.biggestSale||0,price);save.news?.unshift({date,title:`${l.playerName} vendido após empréstimo`,body:`${l.buyerName||'O clube comprador'} executou a cláusula de compra.`});l.purchaseExecuted=true;l.purchasePrice=price;return true}
export function processLoans(save,date){save.loans??=[];save.acquiredPlayerIds??=[];const ended=[];for(const l of save.loans){if(!l.active||l.end>date)continue;l.active=false;ended.push(l);const kind=l.optionKind||(l.buyObligation?'OBLIGATION':l.buyOption?'OPTION':'NONE'),price=Number(l.optionValue||l.buyObligation||l.buyOption||0);if(l.direction==='IN'){let bought=false;if(kind==='OBLIGATION')bought=buyLoanedIn(save,l,date,price);else if(kind==='OPTION'&&price>0){const value=Number(l.marketValueAtStart||price);const exercise=price<=value*1.08&&Math.random()<.58;if(exercise)bought=buyLoanedIn(save,l,date,price)}if(!bought){save.acquiredPlayerIds=save.acquiredPlayerIds.filter(id=>String(id)!==String(l.playerId));save.news?.unshift({date,title:`Fim do empréstimo de ${l.playerName}`,body:kind==='OBLIGATION'&&price>0?'A obrigação não pôde ser executada por falta de verba; o jogador retorna ao clube de origem.':`${l.playerName} retorna ao ${l.parentClubName||'clube de origem'}.`})}}else if(l.direction==='OUT'){let sold=false;if(kind==='OBLIGATION')sold=sellLoanedOut(save,l,date,price);else if(kind==='OPTION'&&price>0){const exercise=Math.random()<.56;if(exercise)sold=sellLoanedOut(save,l,date,price)}if(!sold)save.news?.unshift({date,title:`${l.playerName} retorna de empréstimo`,body:kind==='OPTION'?'O clube não exerceu a opção de compra. O jogador volta ao elenco profissional.':'O jogador volta a ficar disponível para o elenco profissional.'})}}return ended}
export function deadlineDay(date){const d=String(date).slice(5,10);return['08-31','09-01','01-31','02-01'].includes(d)}
