import {transferWindow} from './transfer-engine.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const addYears=(date,years)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString().slice(0,10)};
const monthsBetween=(a,b)=>{if(!a||!b)return 999;const x=new Date(`${a}T12:00:00Z`),y=new Date(`${b}T12:00:00Z`);return Math.round((y-x)/2629800000)};
const hash=s=>[...String(s)].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261)>>>0;
const unit=(seed,n)=>(((Math.imul(seed^(n*2654435761),1664525)+1013904223)>>>0)/4294967296);
const styles=['BALANCED','SPENDER','BARGAIN','AGGRESSIVE'];
function group(p){const x=`${p.position||''} ${p.subPosition||''}`.toLowerCase();if(/goal|keeper/.test(x))return'Goalkeeper';if(/defen|back/.test(x))return'Defence';if(/mid|wing/.test(x))return'Midfield';return'Attack'}
function ensureAiClub(save,c){const seed=hash(c.id||c.name),old=save.aiClubs[c.id]||{};old.ambition??=35+Math.floor(unit(seed,1)*60);old.patience??=35+Math.floor(unit(seed,2)*60);old.transferActivity??=30+Math.floor(unit(seed,3)*65);old.academyFocus??=30+Math.floor(unit(seed,4)*65);old.negotiationStyle??=styles[Math.floor(unit(seed,5)*styles.length)];old.loanPreference??=25+Math.floor(unit(seed,6)*65);old.youthBias??=25+Math.floor(unit(seed,7)*70);old.experienceBias??=25+Math.floor(unit(seed,8)*70);old.riskTolerance??=30+Math.floor(unit(seed,9)*65);save.aiClubs[c.id]=old;return old}
export function ensureWorldSimulation(save,world){save.worldPlayerMoves??={};save.worldContractOverrides??={};save.worldCoachOverrides??={};save.worldFreeCoaches??=[];save.worldNews??=[];save.aiClubs??={};for(const c of world.clubs||[])ensureAiClub(save,c);return save}
export function applyWorldOverrides(save,world){ensureWorldSimulation(save,world);if(world.players){for(const p of world.players){const m=save.worldPlayerMoves[p.id];if(m){p.currentClubId=String(m.clubId);p.currentClubName=m.clubName}const contract=save.worldContractOverrides[p.id];if(contract?.until)p.contractExpiration=contract.until}}for(const c of world.clubs){const name=save.worldCoachOverrides[c.id];if(name)c.coachName=name}return world}
function needScore(world,club,player){const squad=(world.players||[]).filter(p=>String(p.currentClubId)===String(club.id)),counts={Goalkeeper:0,Defence:0,Midfield:0,Attack:0},target={Goalkeeper:3,Defence:8,Midfield:8,Attack:5};squad.forEach(p=>counts[group(p)]++);return clamp((target[group(player)]||5)-(counts[group(player)]||0),-3,4)}
function chooseDestination(player,world,fromId,userClubId,save){const candidates=world.clubs.filter(c=>String(c.id)!==String(fromId)&&String(c.id)!==String(userClubId)&&(c.teamOverall||70)>=(player.overall||65)-8&&(c.teamOverall||70)<=(player.overall||65)+11);if(!candidates.length)return null;const ranked=candidates.map(c=>{const ai=ensureAiClub(save,c),need=needScore(world,c,player),gap=Math.abs((c.teamOverall||70)-(player.overall||65));let score=(ai.ambition||50)*.65+(ai.transferActivity||50)*.72+need*18-gap*2.5;if((player.age||30)<=22)score+=(ai.youthBias||50)*.22;if((player.age||25)>=29)score+=(ai.experienceBias||50)*.18;if(ai.negotiationStyle==='SPENDER')score+=8;if(ai.negotiationStyle==='AGGRESSIVE')score+=5;return{club:c,score}}).sort((a,b)=>b.score-a.score);const pool=ranked.slice(0,Math.min(8,ranked.length));return pool[Math.floor(Math.random()*Math.min(4,pool.length))]?.club||ranked[0].club}
function transferFactor(ai){return ai.negotiationStyle==='SPENDER'?1.12:ai.negotiationStyle==='BARGAIN'?.88:ai.negotiationStyle==='AGGRESSIVE'?1.05:1}
function playerTransferEvents(save,world,date,userClubId){const events=[];if(!world.players||Math.random()>.52)return events;const movable=world.players.filter(p=>String(p.currentClubId)!==String(userClubId)&&!String(p.id).startsWith('youth-')&&transferWindow(world.findClub(p.currentClubId)?.country||'',date).open);const count=Math.min(movable.length,Math.random()<.14?3:Math.random()<.42?2:1),picked=new Set();for(let i=0;i<count;i++){let p=null;for(let tries=0;tries<12&&!p;tries++){const candidate=movable[Math.floor(Math.random()*movable.length)];if(candidate&&!picked.has(String(candidate.id)))p=candidate}if(!p)continue;picked.add(String(p.id));const from=world.findClub(p.currentClubId),to=chooseDestination(p,world,p.currentClubId,userClubId,save);if(!from||!to)continue;const ai=ensureAiClub(save,to),factor=transferFactor(ai),fee=Math.round(Math.max(0,p.marketValue||0)*(.75+Math.random()*.55)*factor/10000)*10000;p.currentClubId=String(to.id);p.currentClubName=to.name;save.worldPlayerMoves[p.id]={clubId:String(to.id),clubName:to.name,date,fee,fromClub:from.name};const reason=needScore(world,to,p)>=2?'para cobrir uma necessidade clara do elenco':(p.age||30)<=22&&ai.youthBias>=65?'como aposta de desenvolvimento':'como reforço para a rotação';events.push({type:'TRANSFER',date,title:`${p.name} muda de clube`,body:`${from.name} → ${to.name} ${reason}${fee?` por valor de jogo estimado em €${Math.round(fee/1e6)}M`:''}.`})}return events}
function renewalEvents(save,world,date,userClubId){const events=[];if(!world.players||Math.random()>.38)return events;const expiring=world.players.filter(p=>String(p.currentClubId)!==String(userClubId)&&p.contractExpiration&&monthsBetween(date,p.contractExpiration)<=8&&monthsBetween(date,p.contractExpiration)>=0);if(!expiring.length)return events;const picked=new Set(),count=Math.min(2,expiring.length);for(let i=0;i<count;i++){let p=null;for(let tries=0;tries<8&&!p;tries++){const candidate=expiring[Math.floor(Math.random()*expiring.length)];if(candidate&&!picked.has(String(candidate.id)))p=candidate}if(!p)continue;picked.add(String(p.id));const club=world.findClub(p.currentClubId);if(!club)continue;const ai=ensureAiClub(save,club),keepChance=.45+(ai.patience||50)/250+(ai.ambition||50)/300;if(Math.random()>keepChance)continue;const years=(p.age||25)>=31?1+Math.floor(Math.random()*2):2+Math.floor(Math.random()*3),until=addYears(date,years);save.worldContractOverrides[p.id]={until,date,clubId:String(club.id)};p.contractExpiration=until;events.push({type:'RENEWAL',date,title:`${p.name} renova com ${club.name}`,body:`O vínculo foi estendido por ${years} ano(s) dentro da carreira.`})}return events}
function uniqueFreeCoaches(save){return[...new Map((save.worldFreeCoaches||[]).filter(x=>x?.name).map(x=>[x.name,x])).values()]}
function coachEvent(save,world,date,userClubId){if(Math.random()>=.07)return null;const candidates=world.clubs.filter(c=>String(c.id)!==String(userClubId)&&c.coachName);if(!candidates.length)return null;const weighted=candidates.map(c=>({club:c,pressure:100-(ensureAiClub(save,c).patience||50)+Math.max(0,78-(c.teamOverall||70))})).sort((a,b)=>b.pressure-a.pressure),club=weighted[Math.floor(Math.random()*Math.min(10,weighted.length))]?.club||candidates[0],old=save.worldCoachOverrides[club.id]||club.coachName;if(!old)return null;const free=uniqueFreeCoaches(save).filter(c=>c.name!==old),employed=world.clubs.filter(c=>String(c.id)!==String(club.id)&&String(c.id)!==String(userClubId)&&c.coachName&&c.coachName!==old);let replacement=null,sourceClub=null;if(free.length&&Math.random()<.72)replacement=free[Math.floor(Math.random()*free.length)]?.name;else if(employed.length){sourceClub=employed[Math.floor(Math.random()*employed.length)];replacement=save.worldCoachOverrides[sourceClub.id]||sourceClub.coachName}if(!replacement)return null;if(sourceClub){save.worldCoachOverrides[sourceClub.id]=old;sourceClub.coachName=old}else save.worldFreeCoaches.push({name:old,date,reputation:club.teamOverall||72,lastClub:club.name});save.worldCoachOverrides[club.id]=replacement;club.coachName=replacement;save.worldFreeCoaches=save.worldFreeCoaches.filter(c=>c.name!==replacement);return{type:'COACH',date,title:`Mudança de técnico no ${club.name}`,body:sourceClub?`${replacement} deixa o ${sourceClub.name} e assume o ${club.name}; ${old} segue o caminho inverso.`:`${old} deixa o cargo. ${replacement} assume o comando.`}}
export function simulateWorldTick(save,world,date,userClubId){ensureWorldSimulation(save,world);const events=[...playerTransferEvents(save,world,date,userClubId),...renewalEvents(save,world,date,userClubId)],coach=coachEvent(save,world,date,userClubId);if(coach)events.push(coach);for(const e of events){save.worldNews.unshift(e);save.news.unshift({date:e.date,title:e.title,body:e.body})}if(save.worldNews.length>300)save.worldNews.length=300;return events}
export function aiClubDecision(save,club){ensureWorldSimulation(save,{clubs:[club]});return save.aiClubs[club.id]||{ambition:50,patience:50,transferActivity:50,academyFocus:50,negotiationStyle:'BALANCED'}}
