import {advanceWorldTransferMarket,ensureWorldTransferMarket} from './world-transfer-market.js';
import {runFreeAgencyTick} from './free-agent-system.js';

const addYears=(date,years)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCFullYear(d.getUTCFullYear()+years);return d.toISOString().slice(0,10)};
const monthsBetween=(a,b)=>{if(!a||!b)return 999;const x=new Date(`${a}T12:00:00Z`),y=new Date(`${b}T12:00:00Z`);return Math.round((y-x)/2629800000)};
const hash=s=>[...String(s)].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261)>>>0;
const unit=(seed,n)=>(((Math.imul(seed^(n*2654435761),1664525)+1013904223)>>>0)/4294967296);
const styles=['BALANCED','SPENDER','BARGAIN','AGGRESSIVE'];

function ensureAiClub(save,c){const seed=hash(c.id||c.name),old=save.aiClubs[c.id]||{};old.ambition??=35+Math.floor(unit(seed,1)*60);old.patience??=35+Math.floor(unit(seed,2)*60);old.transferActivity??=30+Math.floor(unit(seed,3)*65);old.academyFocus??=30+Math.floor(unit(seed,4)*65);old.negotiationStyle??=styles[Math.floor(unit(seed,5)*styles.length)];old.loanPreference??=25+Math.floor(unit(seed,6)*65);old.youthBias??=25+Math.floor(unit(seed,7)*70);old.experienceBias??=25+Math.floor(unit(seed,8)*70);old.riskTolerance??=30+Math.floor(unit(seed,9)*65);save.aiClubs[c.id]=old;return old}
export function ensureWorldSimulation(save,world){save.worldPlayerMoves??={};save.worldContractOverrides??={};save.worldCoachOverrides??={};save.worldFreeCoaches??=[];save.worldNews??=[];save.aiClubs??={};for(const c of world.clubs||[])ensureAiClub(save,c);ensureWorldTransferMarket(save);return save}
export function applyWorldOverrides(save,world){ensureWorldSimulation(save,world);if(world.players){for(const p of world.players){const m=save.worldPlayerMoves[p.id];if(m){p.currentClubId=String(m.clubId);p.currentClubName=m.clubName}const contract=save.worldContractOverrides[p.id];if(contract&&Object.prototype.hasOwnProperty.call(contract,'until'))p.contractExpiration=contract.until||''}}for(const c of world.clubs){const name=save.worldCoachOverrides[c.id];if(name)c.coachName=name}return world}

function renewalEvents(save,world,date,userClubId){const events=[],seed=hash(`${date}|renewals`);if(!world.players||unit(seed,1)>.46)return events;const expiring=world.players.filter(p=>String(p.currentClubId)!==String(userClubId)&&String(p.currentClubId)!=='FREE'&&p.contractExpiration&&monthsBetween(date,p.contractExpiration)<=8&&monthsBetween(date,p.contractExpiration)>=0);if(!expiring.length)return events;const count=Math.min(2,expiring.length);for(let i=0;i<count;i++){const p=expiring[Math.floor(unit(seed,i+2)*expiring.length)],club=world.findClub(p?.currentClubId);if(!p||!club)continue;const a=ensureAiClub(save,club),keepChance=.44+(a.patience||50)/250+(a.ambition||50)/320;if(unit(hash(`${date}|${p.id}|renew`),1)>keepChance)continue;const years=(p.age||25)>=31?1+Math.floor(unit(seed,i+7)*2):2+Math.floor(unit(seed,i+7)*3),until=addYears(date,years);save.worldContractOverrides[p.id]={until,date,clubId:String(club.id),status:'RENEWED'};p.contractExpiration=until;events.push({type:'RENEWAL',date,title:`${p.name} renova com ${club.name}`,body:`O vínculo foi estendido por ${years} ano(s) dentro da carreira.`})}return events}
function uniqueFreeCoaches(save){return[...new Map((save.worldFreeCoaches||[]).filter(x=>x?.name).map(x=>[x.name,x])).values()]}
function coachEvent(save,world,date,userClubId){const seed=hash(`${date}|coach-change|${save.matches?.length||0}`);if(unit(seed,1)>=.09)return null;const candidates=world.clubs.filter(c=>String(c.id)!==String(userClubId)&&c.coachName);if(!candidates.length)return null;const weighted=candidates.map(c=>({club:c,pressure:100-(ensureAiClub(save,c).patience||50)+Math.max(0,78-(c.teamOverall||70))})).sort((a,b)=>b.pressure-a.pressure),club=weighted[Math.floor(unit(seed,2)*Math.min(10,weighted.length))]?.club||candidates[0],old=save.worldCoachOverrides[club.id]||club.coachName;if(!old)return null;const free=uniqueFreeCoaches(save).filter(c=>c.name!==old),employed=world.clubs.filter(c=>String(c.id)!==String(club.id)&&String(c.id)!==String(userClubId)&&c.coachName&&c.coachName!==old);let replacement=null,sourceClub=null;if(free.length&&unit(seed,3)<.72)replacement=free[Math.floor(unit(seed,4)*free.length)]?.name;else if(employed.length){sourceClub=employed[Math.floor(unit(seed,5)*employed.length)];replacement=save.worldCoachOverrides[sourceClub.id]||sourceClub.coachName}if(!replacement)return null;if(sourceClub){save.worldCoachOverrides[sourceClub.id]=old;sourceClub.coachName=old}else save.worldFreeCoaches.push({name:old,date,reputation:club.teamOverall||72,lastClub:club.name});save.worldCoachOverrides[club.id]=replacement;club.coachName=replacement;save.worldFreeCoaches=save.worldFreeCoaches.filter(c=>c.name!==replacement);return{type:'COACH',date,title:`Mudança de técnico no ${club.name}`,body:sourceClub?`${replacement} deixa o ${sourceClub.name} e assume o ${club.name}; ${old} segue o caminho inverso.`:`${old} deixa o cargo. ${replacement} assume o comando.`}}

export function simulateWorldTick(save,world,date,userClubId){ensureWorldSimulation(save,world);save.date=date;const events=[...advanceWorldTransferMarket(save,world,date,userClubId),...runFreeAgencyTick(save,world,date,userClubId),...renewalEvents(save,world,date,userClubId)],coach=coachEvent(save,world,date,userClubId);if(coach)events.push(coach);for(const e of events){save.worldNews.unshift(e);save.news.unshift({date:e.date,title:e.title,body:e.body})}if(save.worldNews.length>400)save.worldNews.length=400;return events}
export function aiClubDecision(save,club){ensureWorldSimulation(save,{clubs:[club]});return save.aiClubs[club.id]||{ambition:50,patience:50,transferActivity:50,academyFocus:50,negotiationStyle:'BALANCED'}}
