import {transferWindow} from './transfer-engine.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function ensureWorldSimulation(save,world){save.worldPlayerMoves??={};save.worldCoachOverrides??={};save.worldFreeCoaches??=[];save.worldNews??=[];save.aiClubs??={};for(const c of world.clubs){save.aiClubs[c.id]??={ambition:35+Math.floor(Math.random()*60),patience:35+Math.floor(Math.random()*60),transferActivity:30+Math.floor(Math.random()*65),academyFocus:30+Math.floor(Math.random()*65)}}return save}
export function applyWorldOverrides(save,world){ensureWorldSimulation(save,world);if(world.players){for(const p of world.players){const m=save.worldPlayerMoves[p.id];if(m){p.currentClubId=String(m.clubId);p.currentClubName=m.clubName}}}for(const c of world.clubs){const name=save.worldCoachOverrides[c.id];if(name)c.coachName=name}return world}
function chooseDestination(player,world,fromId,userClubId){const candidates=world.clubs.filter(c=>String(c.id)!==String(fromId)&&String(c.id)!==String(userClubId)&&(c.teamOverall||70)>=(player.overall||65)-8&&(c.teamOverall||70)<=(player.overall||65)+10);return candidates[Math.floor(Math.random()*candidates.length)]||null}
export function simulateWorldTick(save,world,date,userClubId){ensureWorldSimulation(save,world);const events=[];if(world.players&&Math.random()<.24){const movable=world.players.filter(p=>String(p.currentClubId)!==String(userClubId)&&!String(p.id).startsWith('youth-')&&transferWindow(world.findClub(p.currentClubId)?.country||'',date).open);const count=Math.min(movable.length,Math.random()<.18?2:1);for(let i=0;i<count;i++){const p=movable[Math.floor(Math.random()*movable.length)],from=world.findClub(p.currentClubId),to=chooseDestination(p,world,p.currentClubId,userClubId);if(!from||!to)continue;const fee=Math.round(Math.max(0,p.marketValue||0)*(.75+Math.random()*.55)/10000)*10000;p.currentClubId=String(to.id);p.currentClubName=to.name;save.worldPlayerMoves[p.id]={clubId:String(to.id),clubName:to.name,date,fee,fromClub:from.name};events.push({type:'TRANSFER',date,title:`${p.name} muda de clube`,body:`${from.name} → ${to.name}${fee?` por valor de jogo estimado em €${Math.round(fee/1e6)}M`:''}.`})}}
 if(Math.random()<.055){const candidates=world.clubs.filter(c=>String(c.id)!==String(userClubId)&&c.coachName);if(candidates.length){const club=candidates[Math.floor(Math.random()*candidates.length)],old=save.worldCoachOverrides[club.id]||club.coachName;if(old){save.worldFreeCoaches.push({name:old,date,reputation:club.teamOverall||72,lastClub:club.name});const pool=world.clubs.filter(c=>c.coachName&&c.coachName!==old&&String(c.id)!==String(club.id));const source=pool[Math.floor(Math.random()*pool.length)],replacement=source?.coachName||`Técnico gerado ${Math.floor(Math.random()*9000+1000)}`;save.worldCoachOverrides[club.id]=replacement;club.coachName=replacement;events.push({type:'COACH',date,title:`Mudança de técnico no ${club.name}`,body:`${old} deixa o cargo. ${replacement} assume o comando.`})}}}
 for(const e of events){save.worldNews.unshift(e);save.news.unshift({date:e.date,title:e.title,body:e.body})}if(save.worldNews.length>250)save.worldNews.length=250;return events}
export function aiClubDecision(save,club){ensureWorldSimulation(save,{clubs:[club]});return save.aiClubs[club.id]||{ambition:50,patience:50,transferActivity:50,academyFocus:50}}
